// proto/poll/poll.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: poll.proto

package pollv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PollService_CreatePoll_FullMethodName      = "/poll.v1.PollService/CreatePoll"
	PollService_GetPoll_FullMethodName         = "/poll.v1.PollService/GetPoll"
	PollService_UpdatePoll_FullMethodName      = "/poll.v1.PollService/UpdatePoll"
	PollService_DeletePoll_FullMethodName      = "/poll.v1.PollService/DeletePoll"
	PollService_GetChatPolls_FullMethodName    = "/poll.v1.PollService/GetChatPolls"
	PollService_Vote_FullMethodName            = "/poll.v1.PollService/Vote"
	PollService_Unvote_FullMethodName          = "/poll.v1.PollService/Unvote"
	PollService_GetResults_FullMethodName      = "/poll.v1.PollService/GetResults"
	PollService_GetMyVote_FullMethodName       = "/poll.v1.PollService/GetMyVote"
	PollService_ClosePoll_FullMethodName       = "/poll.v1.PollService/ClosePoll"
	PollService_ReopenPoll_FullMethodName      = "/poll.v1.PollService/ReopenPoll"
	PollService_GetPollInternal_FullMethodName = "/poll.v1.PollService/GetPollInternal"
)

// PollServiceClient is the client API for PollService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== POLL SERVICE ====================
type PollServiceClient interface {
	// Управление опросами
	CreatePoll(ctx context.Context, in *CreatePollRequest, opts ...grpc.CallOption) (*Poll, error)
	GetPoll(ctx context.Context, in *GetPollRequest, opts ...grpc.CallOption) (*Poll, error)
	UpdatePoll(ctx context.Context, in *UpdatePollRequest, opts ...grpc.CallOption) (*Poll, error)
	DeletePoll(ctx context.Context, in *DeletePollRequest, opts ...grpc.CallOption) (*Empty, error)
	GetChatPolls(ctx context.Context, in *GetChatPollsRequest, opts ...grpc.CallOption) (*GetChatPollsResponse, error)
	// Голосование
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	Unvote(ctx context.Context, in *UnvoteRequest, opts ...grpc.CallOption) (*Empty, error)
	GetResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*PollResults, error)
	GetMyVote(ctx context.Context, in *GetMyVoteRequest, opts ...grpc.CallOption) (*GetMyVoteResponse, error)
	// Закрытие/открытие
	ClosePoll(ctx context.Context, in *ClosePollRequest, opts ...grpc.CallOption) (*Poll, error)
	ReopenPoll(ctx context.Context, in *ReopenPollRequest, opts ...grpc.CallOption) (*Poll, error)
	// Внутренние методы для других сервисов
	GetPollInternal(ctx context.Context, in *GetPollInternalRequest, opts ...grpc.CallOption) (*PollInternal, error)
}

type pollServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPollServiceClient(cc grpc.ClientConnInterface) PollServiceClient {
	return &pollServiceClient{cc}
}

func (c *pollServiceClient) CreatePoll(ctx context.Context, in *CreatePollRequest, opts ...grpc.CallOption) (*Poll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Poll)
	err := c.cc.Invoke(ctx, PollService_CreatePoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) GetPoll(ctx context.Context, in *GetPollRequest, opts ...grpc.CallOption) (*Poll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Poll)
	err := c.cc.Invoke(ctx, PollService_GetPoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) UpdatePoll(ctx context.Context, in *UpdatePollRequest, opts ...grpc.CallOption) (*Poll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Poll)
	err := c.cc.Invoke(ctx, PollService_UpdatePoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) DeletePoll(ctx context.Context, in *DeletePollRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PollService_DeletePoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) GetChatPolls(ctx context.Context, in *GetChatPollsRequest, opts ...grpc.CallOption) (*GetChatPollsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatPollsResponse)
	err := c.cc.Invoke(ctx, PollService_GetChatPolls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, PollService_Vote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) Unvote(ctx context.Context, in *UnvoteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PollService_Unvote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) GetResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*PollResults, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollResults)
	err := c.cc.Invoke(ctx, PollService_GetResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) GetMyVote(ctx context.Context, in *GetMyVoteRequest, opts ...grpc.CallOption) (*GetMyVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyVoteResponse)
	err := c.cc.Invoke(ctx, PollService_GetMyVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) ClosePoll(ctx context.Context, in *ClosePollRequest, opts ...grpc.CallOption) (*Poll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Poll)
	err := c.cc.Invoke(ctx, PollService_ClosePoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) ReopenPoll(ctx context.Context, in *ReopenPollRequest, opts ...grpc.CallOption) (*Poll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Poll)
	err := c.cc.Invoke(ctx, PollService_ReopenPoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) GetPollInternal(ctx context.Context, in *GetPollInternalRequest, opts ...grpc.CallOption) (*PollInternal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollInternal)
	err := c.cc.Invoke(ctx, PollService_GetPollInternal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PollServiceServer is the server API for PollService service.
// All implementations must embed UnimplementedPollServiceServer
// for forward compatibility.
//
// ==================== POLL SERVICE ====================
type PollServiceServer interface {
	// Управление опросами
	CreatePoll(context.Context, *CreatePollRequest) (*Poll, error)
	GetPoll(context.Context, *GetPollRequest) (*Poll, error)
	UpdatePoll(context.Context, *UpdatePollRequest) (*Poll, error)
	DeletePoll(context.Context, *DeletePollRequest) (*Empty, error)
	GetChatPolls(context.Context, *GetChatPollsRequest) (*GetChatPollsResponse, error)
	// Голосование
	Vote(context.Context, *VoteRequest) (*VoteResponse, error)
	Unvote(context.Context, *UnvoteRequest) (*Empty, error)
	GetResults(context.Context, *GetResultsRequest) (*PollResults, error)
	GetMyVote(context.Context, *GetMyVoteRequest) (*GetMyVoteResponse, error)
	// Закрытие/открытие
	ClosePoll(context.Context, *ClosePollRequest) (*Poll, error)
	ReopenPoll(context.Context, *ReopenPollRequest) (*Poll, error)
	// Внутренние методы для других сервисов
	GetPollInternal(context.Context, *GetPollInternalRequest) (*PollInternal, error)
	mustEmbedUnimplementedPollServiceServer()
}

// UnimplementedPollServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPollServiceServer struct{}

func (UnimplementedPollServiceServer) CreatePoll(context.Context, *CreatePollRequest) (*Poll, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePoll not implemented")
}
func (UnimplementedPollServiceServer) GetPoll(context.Context, *GetPollRequest) (*Poll, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPoll not implemented")
}
func (UnimplementedPollServiceServer) UpdatePoll(context.Context, *UpdatePollRequest) (*Poll, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePoll not implemented")
}
func (UnimplementedPollServiceServer) DeletePoll(context.Context, *DeletePollRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePoll not implemented")
}
func (UnimplementedPollServiceServer) GetChatPolls(context.Context, *GetChatPollsRequest) (*GetChatPollsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatPolls not implemented")
}
func (UnimplementedPollServiceServer) Vote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Vote not implemented")
}
func (UnimplementedPollServiceServer) Unvote(context.Context, *UnvoteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Unvote not implemented")
}
func (UnimplementedPollServiceServer) GetResults(context.Context, *GetResultsRequest) (*PollResults, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResults not implemented")
}
func (UnimplementedPollServiceServer) GetMyVote(context.Context, *GetMyVoteRequest) (*GetMyVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyVote not implemented")
}
func (UnimplementedPollServiceServer) ClosePoll(context.Context, *ClosePollRequest) (*Poll, error) {
	return nil, status.Error(codes.Unimplemented, "method ClosePoll not implemented")
}
func (UnimplementedPollServiceServer) ReopenPoll(context.Context, *ReopenPollRequest) (*Poll, error) {
	return nil, status.Error(codes.Unimplemented, "method ReopenPoll not implemented")
}
func (UnimplementedPollServiceServer) GetPollInternal(context.Context, *GetPollInternalRequest) (*PollInternal, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPollInternal not implemented")
}
func (UnimplementedPollServiceServer) mustEmbedUnimplementedPollServiceServer() {}
func (UnimplementedPollServiceServer) testEmbeddedByValue()                     {}

// UnsafePollServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PollServiceServer will
// result in compilation errors.
type UnsafePollServiceServer interface {
	mustEmbedUnimplementedPollServiceServer()
}

func RegisterPollServiceServer(s grpc.ServiceRegistrar, srv PollServiceServer) {
	// If the following call panics, it indicates UnimplementedPollServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PollService_ServiceDesc, srv)
}

func _PollService_CreatePoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).CreatePoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_CreatePoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).CreatePoll(ctx, req.(*CreatePollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_GetPoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).GetPoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_GetPoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).GetPoll(ctx, req.(*GetPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_UpdatePoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).UpdatePoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_UpdatePoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).UpdatePoll(ctx, req.(*UpdatePollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_DeletePoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).DeletePoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_DeletePoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).DeletePoll(ctx, req.(*DeletePollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_GetChatPolls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatPollsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).GetChatPolls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_GetChatPolls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).GetChatPolls(ctx, req.(*GetChatPollsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_Vote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_Unvote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnvoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).Unvote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_Unvote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).Unvote(ctx, req.(*UnvoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_GetResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).GetResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_GetResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).GetResults(ctx, req.(*GetResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_GetMyVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).GetMyVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_GetMyVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).GetMyVote(ctx, req.(*GetMyVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_ClosePoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).ClosePoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_ClosePoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).ClosePoll(ctx, req.(*ClosePollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_ReopenPoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReopenPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).ReopenPoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_ReopenPoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).ReopenPoll(ctx, req.(*ReopenPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_GetPollInternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPollInternalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).GetPollInternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_GetPollInternal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).GetPollInternal(ctx, req.(*GetPollInternalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PollService_ServiceDesc is the grpc.ServiceDesc for PollService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PollService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poll.v1.PollService",
	HandlerType: (*PollServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePoll",
			Handler:    _PollService_CreatePoll_Handler,
		},
		{
			MethodName: "GetPoll",
			Handler:    _PollService_GetPoll_Handler,
		},
		{
			MethodName: "UpdatePoll",
			Handler:    _PollService_UpdatePoll_Handler,
		},
		{
			MethodName: "DeletePoll",
			Handler:    _PollService_DeletePoll_Handler,
		},
		{
			MethodName: "GetChatPolls",
			Handler:    _PollService_GetChatPolls_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _PollService_Vote_Handler,
		},
		{
			MethodName: "Unvote",
			Handler:    _PollService_Unvote_Handler,
		},
		{
			MethodName: "GetResults",
			Handler:    _PollService_GetResults_Handler,
		},
		{
			MethodName: "GetMyVote",
			Handler:    _PollService_GetMyVote_Handler,
		},
		{
			MethodName: "ClosePoll",
			Handler:    _PollService_ClosePoll_Handler,
		},
		{
			MethodName: "ReopenPoll",
			Handler:    _PollService_ReopenPoll_Handler,
		},
		{
			MethodName: "GetPollInternal",
			Handler:    _PollService_GetPollInternal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poll.proto",
}
