// proto/poll/poll.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: poll.proto

package pollv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollStatus int32

const (
	PollStatus_POLL_STATUS_UNKNOWN PollStatus = 0
	PollStatus_POLL_STATUS_ACTIVE  PollStatus = 1 // Активный
	PollStatus_POLL_STATUS_CLOSED  PollStatus = 2 // Закрыт
)

// Enum value maps for PollStatus.
var (
	PollStatus_name = map[int32]string{
		0: "POLL_STATUS_UNKNOWN",
		1: "POLL_STATUS_ACTIVE",
		2: "POLL_STATUS_CLOSED",
	}
	PollStatus_value = map[string]int32{
		"POLL_STATUS_UNKNOWN": 0,
		"POLL_STATUS_ACTIVE":  1,
		"POLL_STATUS_CLOSED":  2,
	}
)

func (x PollStatus) Enum() *PollStatus {
	p := new(PollStatus)
	*p = x
	return p
}

func (x PollStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PollStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_poll_proto_enumTypes[0].Descriptor()
}

func (PollStatus) Type() protoreflect.EnumType {
	return &file_poll_proto_enumTypes[0]
}

func (x PollStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PollStatus.Descriptor instead.
func (PollStatus) EnumDescriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_poll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{0}
}

// Создание опроса
type CreatePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"` // ID чата
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`           // Вопрос опроса
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`             // Варианты ответов (минимум 2, максимум 10)
	Settings      *PollSettings          `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`           // Настройки опроса
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePollRequest) Reset() {
	*x = CreatePollRequest{}
	mi := &file_poll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePollRequest) ProtoMessage() {}

func (x *CreatePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePollRequest.ProtoReflect.Descriptor instead.
func (*CreatePollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePollRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CreatePollRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CreatePollRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreatePollRequest) GetSettings() *PollSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Poll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // ID создателя
	Question      string                 `protobuf:"bytes,4,opt,name=question,proto3" json:"question,omitempty"`
	Options       []*PollOption          `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	Settings      *PollSettings          `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	Status        PollStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=poll.v1.PollStatus" json:"status,omitempty"`   // active/closed
	TotalVotes    int32                  `protobuf:"varint,8,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"` // Общее количество голосов
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poll) Reset() {
	*x = Poll{}
	mi := &file_poll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poll.ProtoReflect.Descriptor instead.
func (*Poll) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{2}
}

func (x *Poll) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Poll) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Poll) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Poll) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Poll) GetOptions() []*PollOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Poll) GetSettings() *PollSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Poll) GetStatus() PollStatus {
	if x != nil {
		return x.Status
	}
	return PollStatus_POLL_STATUS_UNKNOWN
}

func (x *Poll) GetTotalVotes() int32 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

func (x *Poll) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Poll) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Poll) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

type PollOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                    // ID варианта (опционально)
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                // Текст варианта
	VotesCount    int32                  `protobuf:"varint,3,opt,name=votes_count,json=votesCount,proto3" json:"votes_count,omitempty"` // Количество голосов
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`                  // Процент (0-100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollOption) Reset() {
	*x = PollOption{}
	mi := &file_poll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollOption) ProtoMessage() {}

func (x *PollOption) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollOption.ProtoReflect.Descriptor instead.
func (*PollOption) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{3}
}

func (x *PollOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PollOption) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PollOption) GetVotesCount() int32 {
	if x != nil {
		return x.VotesCount
	}
	return 0
}

func (x *PollOption) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type PollSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IsAnonymous          bool                   `protobuf:"varint,1,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`                                // Анонимное голосование (по умолчанию false)
	AllowMultiple        bool                   `protobuf:"varint,2,opt,name=allow_multiple,json=allowMultiple,proto3" json:"allow_multiple,omitempty"`                          // Можно выбрать несколько вариантов (по умолчанию false)
	MaxVotes             int32                  `protobuf:"varint,3,opt,name=max_votes,json=maxVotes,proto3" json:"max_votes,omitempty"`                                         // Максимум голосов (если allow_multiple = true)
	AllowChangeVote      bool                   `protobuf:"varint,4,opt,name=allow_change_vote,json=allowChangeVote,proto3" json:"allow_change_vote,omitempty"`                  // Можно менять голос (по умолчанию true)
	EndsAt               *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`                                                // Когда заканчивается (опционально)
	ShowResultsBeforeEnd bool                   `protobuf:"varint,6,opt,name=show_results_before_end,json=showResultsBeforeEnd,proto3" json:"show_results_before_end,omitempty"` // Показывать результаты до окончания (по умолчанию true)
	ShowWhoVoted         bool                   `protobuf:"varint,7,opt,name=show_who_voted,json=showWhoVoted,proto3" json:"show_who_voted,omitempty"`                           // Показывать кто голосовал (по умолчанию false)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PollSettings) Reset() {
	*x = PollSettings{}
	mi := &file_poll_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollSettings) ProtoMessage() {}

func (x *PollSettings) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollSettings.ProtoReflect.Descriptor instead.
func (*PollSettings) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{4}
}

func (x *PollSettings) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *PollSettings) GetAllowMultiple() bool {
	if x != nil {
		return x.AllowMultiple
	}
	return false
}

func (x *PollSettings) GetMaxVotes() int32 {
	if x != nil {
		return x.MaxVotes
	}
	return 0
}

func (x *PollSettings) GetAllowChangeVote() bool {
	if x != nil {
		return x.AllowChangeVote
	}
	return false
}

func (x *PollSettings) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *PollSettings) GetShowResultsBeforeEnd() bool {
	if x != nil {
		return x.ShowResultsBeforeEnd
	}
	return false
}

func (x *PollSettings) GetShowWhoVoted() bool {
	if x != nil {
		return x.ShowWhoVoted
	}
	return false
}

// Получение опроса
type GetPollRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PollId         string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	IncludeResults bool                   `protobuf:"varint,2,opt,name=include_results,json=includeResults,proto3" json:"include_results,omitempty"` // Включить результаты (по умолчанию true)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPollRequest) Reset() {
	*x = GetPollRequest{}
	mi := &file_poll_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollRequest) ProtoMessage() {}

func (x *GetPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollRequest.ProtoReflect.Descriptor instead.
func (*GetPollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{5}
}

func (x *GetPollRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *GetPollRequest) GetIncludeResults() bool {
	if x != nil {
		return x.IncludeResults
	}
	return false
}

// Обновление опроса
type UpdatePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Question      *string                `protobuf:"bytes,2,opt,name=question,proto3,oneof" json:"question,omitempty"` // Новый вопрос
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`         // Новые варианты (перезапишет существующие)
	Settings      *PollSettings          `protobuf:"bytes,4,opt,name=settings,proto3,oneof" json:"settings,omitempty"` // Новые настройки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePollRequest) Reset() {
	*x = UpdatePollRequest{}
	mi := &file_poll_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePollRequest) ProtoMessage() {}

func (x *UpdatePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePollRequest.ProtoReflect.Descriptor instead.
func (*UpdatePollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePollRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *UpdatePollRequest) GetQuestion() string {
	if x != nil && x.Question != nil {
		return *x.Question
	}
	return ""
}

func (x *UpdatePollRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *UpdatePollRequest) GetSettings() *PollSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Удаление опроса
type DeletePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePollRequest) Reset() {
	*x = DeletePollRequest{}
	mi := &file_poll_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePollRequest) ProtoMessage() {}

func (x *DeletePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePollRequest.ProtoReflect.Descriptor instead.
func (*DeletePollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePollRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

// Получить опросы чата
type GetChatPollsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                           // Максимум опросов (max 50)
	Status        PollStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=poll.v1.PollStatus" json:"status,omitempty"` // Фильтр по статусу
	Before        string                 `protobuf:"bytes,4,opt,name=before,proto3" json:"before,omitempty"`                          // Пагинация: ID опроса, до которого грузить
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatPollsRequest) Reset() {
	*x = GetChatPollsRequest{}
	mi := &file_poll_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatPollsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatPollsRequest) ProtoMessage() {}

func (x *GetChatPollsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatPollsRequest.ProtoReflect.Descriptor instead.
func (*GetChatPollsRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{8}
}

func (x *GetChatPollsRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetChatPollsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatPollsRequest) GetStatus() PollStatus {
	if x != nil {
		return x.Status
	}
	return PollStatus_POLL_STATUS_UNKNOWN
}

func (x *GetChatPollsRequest) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

type GetChatPollsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polls         []*Poll                `protobuf:"bytes,1,rep,name=polls,proto3" json:"polls,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatPollsResponse) Reset() {
	*x = GetChatPollsResponse{}
	mi := &file_poll_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatPollsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatPollsResponse) ProtoMessage() {}

func (x *GetChatPollsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatPollsResponse.ProtoReflect.Descriptor instead.
func (*GetChatPollsResponse) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{9}
}

func (x *GetChatPollsResponse) GetPolls() []*Poll {
	if x != nil {
		return x.Polls
	}
	return nil
}

func (x *GetChatPollsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Голосование
type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	OptionIds     []string               `protobuf:"bytes,2,rep,name=option_ids,json=optionIds,proto3" json:"option_ids,omitempty"`                     // ID выбранных вариантов (если allow_multiple)
	OptionIndexes []int32                `protobuf:"varint,3,rep,packed,name=option_indexes,json=optionIndexes,proto3" json:"option_indexes,omitempty"` // ИЛИ индексы вариантов (0-based)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_poll_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{10}
}

func (x *VoteRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *VoteRequest) GetOptionIds() []string {
	if x != nil {
		return x.OptionIds
	}
	return nil
}

func (x *VoteRequest) GetOptionIndexes() []int32 {
	if x != nil {
		return x.OptionIndexes
	}
	return nil
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       *PollResults           `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"`                             // Обновлённые результаты
	VoteUpdated   bool                   `protobuf:"varint,2,opt,name=vote_updated,json=voteUpdated,proto3" json:"vote_updated,omitempty"` // Был ли обновлён предыдущий голос
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_poll_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{11}
}

func (x *VoteResponse) GetResults() *PollResults {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *VoteResponse) GetVoteUpdated() bool {
	if x != nil {
		return x.VoteUpdated
	}
	return false
}

// Отмена голоса
type UnvoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnvoteRequest) Reset() {
	*x = UnvoteRequest{}
	mi := &file_poll_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnvoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnvoteRequest) ProtoMessage() {}

func (x *UnvoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnvoteRequest.ProtoReflect.Descriptor instead.
func (*UnvoteRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{12}
}

func (x *UnvoteRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

// Результаты
type GetResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	IncludeVoters bool                   `protobuf:"varint,2,opt,name=include_voters,json=includeVoters,proto3" json:"include_voters,omitempty"` // Включить список проголосовавших (если разрешено)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultsRequest) Reset() {
	*x = GetResultsRequest{}
	mi := &file_poll_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultsRequest) ProtoMessage() {}

func (x *GetResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultsRequest.ProtoReflect.Descriptor instead.
func (*GetResultsRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{13}
}

func (x *GetResultsRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *GetResultsRequest) GetIncludeVoters() bool {
	if x != nil {
		return x.IncludeVoters
	}
	return false
}

type PollResults struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	PollId        string                   `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Question      string                   `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Options       []*PollOption            `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	TotalVotes    int32                    `protobuf:"varint,4,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	Status        PollStatus               `protobuf:"varint,5,opt,name=status,proto3,enum=poll.v1.PollStatus" json:"status,omitempty"`
	Voters        map[string]*OptionVoters `protobuf:"bytes,6,rep,name=voters,proto3" json:"voters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // option_id -> список проголосовавших (если не анонимно)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResults) Reset() {
	*x = PollResults{}
	mi := &file_poll_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResults) ProtoMessage() {}

func (x *PollResults) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResults.ProtoReflect.Descriptor instead.
func (*PollResults) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{14}
}

func (x *PollResults) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *PollResults) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *PollResults) GetOptions() []*PollOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PollResults) GetTotalVotes() int32 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

func (x *PollResults) GetStatus() PollStatus {
	if x != nil {
		return x.Status
	}
	return PollStatus_POLL_STATUS_UNKNOWN
}

func (x *PollResults) GetVoters() map[string]*OptionVoters {
	if x != nil {
		return x.Voters
	}
	return nil
}

type OptionVoters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	VotersInfo    []*VoterInfo           `protobuf:"bytes,2,rep,name=voters_info,json=votersInfo,proto3" json:"voters_info,omitempty"` // Детальная информация о пользователях
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionVoters) Reset() {
	*x = OptionVoters{}
	mi := &file_poll_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionVoters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionVoters) ProtoMessage() {}

func (x *OptionVoters) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionVoters.ProtoReflect.Descriptor instead.
func (*OptionVoters) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{15}
}

func (x *OptionVoters) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *OptionVoters) GetVotersInfo() []*VoterInfo {
	if x != nil {
		return x.VotersInfo
	}
	return nil
}

type VoterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoterInfo) Reset() {
	*x = VoterInfo{}
	mi := &file_poll_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoterInfo) ProtoMessage() {}

func (x *VoterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoterInfo.ProtoReflect.Descriptor instead.
func (*VoterInfo) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{16}
}

func (x *VoterInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VoterInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VoterInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *VoterInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// Мой голос
type GetMyVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyVoteRequest) Reset() {
	*x = GetMyVoteRequest{}
	mi := &file_poll_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyVoteRequest) ProtoMessage() {}

func (x *GetMyVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyVoteRequest.ProtoReflect.Descriptor instead.
func (*GetMyVoteRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{17}
}

func (x *GetMyVoteRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

type GetMyVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasVoted      bool                   `protobuf:"varint,1,opt,name=has_voted,json=hasVoted,proto3" json:"has_voted,omitempty"`
	OptionIds     []string               `protobuf:"bytes,2,rep,name=option_ids,json=optionIds,proto3" json:"option_ids,omitempty"`                     // ID выбранных вариантов
	OptionIndexes []int32                `protobuf:"varint,3,rep,packed,name=option_indexes,json=optionIndexes,proto3" json:"option_indexes,omitempty"` // Индексы выбранных вариантов
	VotedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=voted_at,json=votedAt,proto3" json:"voted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyVoteResponse) Reset() {
	*x = GetMyVoteResponse{}
	mi := &file_poll_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyVoteResponse) ProtoMessage() {}

func (x *GetMyVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyVoteResponse.ProtoReflect.Descriptor instead.
func (*GetMyVoteResponse) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{18}
}

func (x *GetMyVoteResponse) GetHasVoted() bool {
	if x != nil {
		return x.HasVoted
	}
	return false
}

func (x *GetMyVoteResponse) GetOptionIds() []string {
	if x != nil {
		return x.OptionIds
	}
	return nil
}

func (x *GetMyVoteResponse) GetOptionIndexes() []int32 {
	if x != nil {
		return x.OptionIndexes
	}
	return nil
}

func (x *GetMyVoteResponse) GetVotedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VotedAt
	}
	return nil
}

// Закрытие/открытие
type ClosePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePollRequest) Reset() {
	*x = ClosePollRequest{}
	mi := &file_poll_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePollRequest) ProtoMessage() {}

func (x *ClosePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePollRequest.ProtoReflect.Descriptor instead.
func (*ClosePollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{19}
}

func (x *ClosePollRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

type ReopenPollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReopenPollRequest) Reset() {
	*x = ReopenPollRequest{}
	mi := &file_poll_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReopenPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReopenPollRequest) ProtoMessage() {}

func (x *ReopenPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReopenPollRequest.ProtoReflect.Descriptor instead.
func (*ReopenPollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{20}
}

func (x *ReopenPollRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

// Внутренние методы
type GetPollInternalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollInternalRequest) Reset() {
	*x = GetPollInternalRequest{}
	mi := &file_poll_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollInternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollInternalRequest) ProtoMessage() {}

func (x *GetPollInternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollInternalRequest.ProtoReflect.Descriptor instead.
func (*GetPollInternalRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{21}
}

func (x *GetPollInternalRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

type PollInternal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"` // Только тексты вариантов
	Status        PollStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=poll.v1.PollStatus" json:"status,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollInternal) Reset() {
	*x = PollInternal{}
	mi := &file_poll_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollInternal) ProtoMessage() {}

func (x *PollInternal) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollInternal.ProtoReflect.Descriptor instead.
func (*PollInternal) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{22}
}

func (x *PollInternal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PollInternal) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *PollInternal) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *PollInternal) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PollInternal) GetStatus() PollStatus {
	if x != nil {
		return x.Status
	}
	return PollStatus_POLL_STATUS_UNKNOWN
}

func (x *PollInternal) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

var File_poll_proto protoreflect.FileDescriptor

const file_poll_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"poll.proto\x12\apoll.v1\x1a\x0ftimestamp.proto\"\a\n" +
	"\x05Empty\"\x95\x01\n" +
	"\x11CreatePollRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x121\n" +
	"\bsettings\x18\x04 \x01(\v2\x15.poll.v1.PollSettingsR\bsettings\"\xc9\x03\n" +
	"\x04Poll\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x12\x1a\n" +
	"\bquestion\x18\x04 \x01(\tR\bquestion\x12-\n" +
	"\aoptions\x18\x05 \x03(\v2\x13.poll.v1.PollOptionR\aoptions\x121\n" +
	"\bsettings\x18\x06 \x01(\v2\x15.poll.v1.PollSettingsR\bsettings\x12+\n" +
	"\x06status\x18\a \x01(\x0e2\x13.poll.v1.PollStatusR\x06status\x12\x1f\n" +
	"\vtotal_votes\x18\b \x01(\x05R\n" +
	"totalVotes\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\tclosed_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\"q\n" +
	"\n" +
	"PollOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1f\n" +
	"\vvotes_count\x18\x03 \x01(\x05R\n" +
	"votesCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\"\xb3\x02\n" +
	"\fPollSettings\x12!\n" +
	"\fis_anonymous\x18\x01 \x01(\bR\visAnonymous\x12%\n" +
	"\x0eallow_multiple\x18\x02 \x01(\bR\rallowMultiple\x12\x1b\n" +
	"\tmax_votes\x18\x03 \x01(\x05R\bmaxVotes\x12*\n" +
	"\x11allow_change_vote\x18\x04 \x01(\bR\x0fallowChangeVote\x123\n" +
	"\aends_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x125\n" +
	"\x17show_results_before_end\x18\x06 \x01(\bR\x14showResultsBeforeEnd\x12$\n" +
	"\x0eshow_who_voted\x18\a \x01(\bR\fshowWhoVoted\"R\n" +
	"\x0eGetPollRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12'\n" +
	"\x0finclude_results\x18\x02 \x01(\bR\x0eincludeResults\"\xb9\x01\n" +
	"\x11UpdatePollRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x1f\n" +
	"\bquestion\x18\x02 \x01(\tH\x00R\bquestion\x88\x01\x01\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x126\n" +
	"\bsettings\x18\x04 \x01(\v2\x15.poll.v1.PollSettingsH\x01R\bsettings\x88\x01\x01B\v\n" +
	"\t_questionB\v\n" +
	"\t_settings\",\n" +
	"\x11DeletePollRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\"\x89\x01\n" +
	"\x13GetChatPollsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.poll.v1.PollStatusR\x06status\x12\x16\n" +
	"\x06before\x18\x04 \x01(\tR\x06before\"V\n" +
	"\x14GetChatPollsResponse\x12#\n" +
	"\x05polls\x18\x01 \x03(\v2\r.poll.v1.PollR\x05polls\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"l\n" +
	"\vVoteRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x1d\n" +
	"\n" +
	"option_ids\x18\x02 \x03(\tR\toptionIds\x12%\n" +
	"\x0eoption_indexes\x18\x03 \x03(\x05R\roptionIndexes\"a\n" +
	"\fVoteResponse\x12.\n" +
	"\aresults\x18\x01 \x01(\v2\x14.poll.v1.PollResultsR\aresults\x12!\n" +
	"\fvote_updated\x18\x02 \x01(\bR\vvoteUpdated\"(\n" +
	"\rUnvoteRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\"S\n" +
	"\x11GetResultsRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12%\n" +
	"\x0einclude_voters\x18\x02 \x01(\bR\rincludeVoters\"\xcb\x02\n" +
	"\vPollResults\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12-\n" +
	"\aoptions\x18\x03 \x03(\v2\x13.poll.v1.PollOptionR\aoptions\x12\x1f\n" +
	"\vtotal_votes\x18\x04 \x01(\x05R\n" +
	"totalVotes\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.poll.v1.PollStatusR\x06status\x128\n" +
	"\x06voters\x18\x06 \x03(\v2 .poll.v1.PollResults.VotersEntryR\x06voters\x1aP\n" +
	"\vVotersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.poll.v1.OptionVotersR\x05value:\x028\x01\"^\n" +
	"\fOptionVoters\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x123\n" +
	"\vvoters_info\x18\x02 \x03(\v2\x12.poll.v1.VoterInfoR\n" +
	"votersInfo\"|\n" +
	"\tVoterInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"+\n" +
	"\x10GetMyVoteRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\"\xad\x01\n" +
	"\x11GetMyVoteResponse\x12\x1b\n" +
	"\thas_voted\x18\x01 \x01(\bR\bhasVoted\x12\x1d\n" +
	"\n" +
	"option_ids\x18\x02 \x03(\tR\toptionIds\x12%\n" +
	"\x0eoption_indexes\x18\x03 \x03(\x05R\roptionIndexes\x125\n" +
	"\bvoted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\avotedAt\"+\n" +
	"\x10ClosePollRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\",\n" +
	"\x11ReopenPollRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\"1\n" +
	"\x16GetPollInternalRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\"\xcf\x01\n" +
	"\fPollInternal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.poll.v1.PollStatusR\x06status\x123\n" +
	"\aends_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt*U\n" +
	"\n" +
	"PollStatus\x12\x17\n" +
	"\x13POLL_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12POLL_STATUS_ACTIVE\x10\x01\x12\x16\n" +
	"\x12POLL_STATUS_CLOSED\x10\x022\xe1\x05\n" +
	"\vPollService\x127\n" +
	"\n" +
	"CreatePoll\x12\x1a.poll.v1.CreatePollRequest\x1a\r.poll.v1.Poll\x121\n" +
	"\aGetPoll\x12\x17.poll.v1.GetPollRequest\x1a\r.poll.v1.Poll\x127\n" +
	"\n" +
	"UpdatePoll\x12\x1a.poll.v1.UpdatePollRequest\x1a\r.poll.v1.Poll\x128\n" +
	"\n" +
	"DeletePoll\x12\x1a.poll.v1.DeletePollRequest\x1a\x0e.poll.v1.Empty\x12K\n" +
	"\fGetChatPolls\x12\x1c.poll.v1.GetChatPollsRequest\x1a\x1d.poll.v1.GetChatPollsResponse\x123\n" +
	"\x04Vote\x12\x14.poll.v1.VoteRequest\x1a\x15.poll.v1.VoteResponse\x120\n" +
	"\x06Unvote\x12\x16.poll.v1.UnvoteRequest\x1a\x0e.poll.v1.Empty\x12>\n" +
	"\n" +
	"GetResults\x12\x1a.poll.v1.GetResultsRequest\x1a\x14.poll.v1.PollResults\x12B\n" +
	"\tGetMyVote\x12\x19.poll.v1.GetMyVoteRequest\x1a\x1a.poll.v1.GetMyVoteResponse\x125\n" +
	"\tClosePoll\x12\x19.poll.v1.ClosePollRequest\x1a\r.poll.v1.Poll\x127\n" +
	"\n" +
	"ReopenPoll\x12\x1a.poll.v1.ReopenPollRequest\x1a\r.poll.v1.Poll\x12K\n" +
	"\x0fGetPollInternal\x12\x1f.poll.v1.GetPollInternalRequest\x1a\x15.poll.v1.PollInternal\"\x00B?Z=github.com/north-fy/talker/services/poll/pkg/protos/v1;pollv1b\x06proto3"

var (
	file_poll_proto_rawDescOnce sync.Once
	file_poll_proto_rawDescData []byte
)

func file_poll_proto_rawDescGZIP() []byte {
	file_poll_proto_rawDescOnce.Do(func() {
		file_poll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poll_proto_rawDesc), len(file_poll_proto_rawDesc)))
	})
	return file_poll_proto_rawDescData
}

var file_poll_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_poll_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_poll_proto_goTypes = []any{
	(PollStatus)(0),                // 0: poll.v1.PollStatus
	(*Empty)(nil),                  // 1: poll.v1.Empty
	(*CreatePollRequest)(nil),      // 2: poll.v1.CreatePollRequest
	(*Poll)(nil),                   // 3: poll.v1.Poll
	(*PollOption)(nil),             // 4: poll.v1.PollOption
	(*PollSettings)(nil),           // 5: poll.v1.PollSettings
	(*GetPollRequest)(nil),         // 6: poll.v1.GetPollRequest
	(*UpdatePollRequest)(nil),      // 7: poll.v1.UpdatePollRequest
	(*DeletePollRequest)(nil),      // 8: poll.v1.DeletePollRequest
	(*GetChatPollsRequest)(nil),    // 9: poll.v1.GetChatPollsRequest
	(*GetChatPollsResponse)(nil),   // 10: poll.v1.GetChatPollsResponse
	(*VoteRequest)(nil),            // 11: poll.v1.VoteRequest
	(*VoteResponse)(nil),           // 12: poll.v1.VoteResponse
	(*UnvoteRequest)(nil),          // 13: poll.v1.UnvoteRequest
	(*GetResultsRequest)(nil),      // 14: poll.v1.GetResultsRequest
	(*PollResults)(nil),            // 15: poll.v1.PollResults
	(*OptionVoters)(nil),           // 16: poll.v1.OptionVoters
	(*VoterInfo)(nil),              // 17: poll.v1.VoterInfo
	(*GetMyVoteRequest)(nil),       // 18: poll.v1.GetMyVoteRequest
	(*GetMyVoteResponse)(nil),      // 19: poll.v1.GetMyVoteResponse
	(*ClosePollRequest)(nil),       // 20: poll.v1.ClosePollRequest
	(*ReopenPollRequest)(nil),      // 21: poll.v1.ReopenPollRequest
	(*GetPollInternalRequest)(nil), // 22: poll.v1.GetPollInternalRequest
	(*PollInternal)(nil),           // 23: poll.v1.PollInternal
	nil,                            // 24: poll.v1.PollResults.VotersEntry
	(*timestamppb.Timestamp)(nil),  // 25: google.protobuf.Timestamp
}
var file_poll_proto_depIdxs = []int32{
	5,  // 0: poll.v1.CreatePollRequest.settings:type_name -> poll.v1.PollSettings
	4,  // 1: poll.v1.Poll.options:type_name -> poll.v1.PollOption
	5,  // 2: poll.v1.Poll.settings:type_name -> poll.v1.PollSettings
	0,  // 3: poll.v1.Poll.status:type_name -> poll.v1.PollStatus
	25, // 4: poll.v1.Poll.created_at:type_name -> google.protobuf.Timestamp
	25, // 5: poll.v1.Poll.updated_at:type_name -> google.protobuf.Timestamp
	25, // 6: poll.v1.Poll.closed_at:type_name -> google.protobuf.Timestamp
	25, // 7: poll.v1.PollSettings.ends_at:type_name -> google.protobuf.Timestamp
	5,  // 8: poll.v1.UpdatePollRequest.settings:type_name -> poll.v1.PollSettings
	0,  // 9: poll.v1.GetChatPollsRequest.status:type_name -> poll.v1.PollStatus
	3,  // 10: poll.v1.GetChatPollsResponse.polls:type_name -> poll.v1.Poll
	15, // 11: poll.v1.VoteResponse.results:type_name -> poll.v1.PollResults
	4,  // 12: poll.v1.PollResults.options:type_name -> poll.v1.PollOption
	0,  // 13: poll.v1.PollResults.status:type_name -> poll.v1.PollStatus
	24, // 14: poll.v1.PollResults.voters:type_name -> poll.v1.PollResults.VotersEntry
	17, // 15: poll.v1.OptionVoters.voters_info:type_name -> poll.v1.VoterInfo
	25, // 16: poll.v1.GetMyVoteResponse.voted_at:type_name -> google.protobuf.Timestamp
	0,  // 17: poll.v1.PollInternal.status:type_name -> poll.v1.PollStatus
	25, // 18: poll.v1.PollInternal.ends_at:type_name -> google.protobuf.Timestamp
	16, // 19: poll.v1.PollResults.VotersEntry.value:type_name -> poll.v1.OptionVoters
	2,  // 20: poll.v1.PollService.CreatePoll:input_type -> poll.v1.CreatePollRequest
	6,  // 21: poll.v1.PollService.GetPoll:input_type -> poll.v1.GetPollRequest
	7,  // 22: poll.v1.PollService.UpdatePoll:input_type -> poll.v1.UpdatePollRequest
	8,  // 23: poll.v1.PollService.DeletePoll:input_type -> poll.v1.DeletePollRequest
	9,  // 24: poll.v1.PollService.GetChatPolls:input_type -> poll.v1.GetChatPollsRequest
	11, // 25: poll.v1.PollService.Vote:input_type -> poll.v1.VoteRequest
	13, // 26: poll.v1.PollService.Unvote:input_type -> poll.v1.UnvoteRequest
	14, // 27: poll.v1.PollService.GetResults:input_type -> poll.v1.GetResultsRequest
	18, // 28: poll.v1.PollService.GetMyVote:input_type -> poll.v1.GetMyVoteRequest
	20, // 29: poll.v1.PollService.ClosePoll:input_type -> poll.v1.ClosePollRequest
	21, // 30: poll.v1.PollService.ReopenPoll:input_type -> poll.v1.ReopenPollRequest
	22, // 31: poll.v1.PollService.GetPollInternal:input_type -> poll.v1.GetPollInternalRequest
	3,  // 32: poll.v1.PollService.CreatePoll:output_type -> poll.v1.Poll
	3,  // 33: poll.v1.PollService.GetPoll:output_type -> poll.v1.Poll
	3,  // 34: poll.v1.PollService.UpdatePoll:output_type -> poll.v1.Poll
	1,  // 35: poll.v1.PollService.DeletePoll:output_type -> poll.v1.Empty
	10, // 36: poll.v1.PollService.GetChatPolls:output_type -> poll.v1.GetChatPollsResponse
	12, // 37: poll.v1.PollService.Vote:output_type -> poll.v1.VoteResponse
	1,  // 38: poll.v1.PollService.Unvote:output_type -> poll.v1.Empty
	15, // 39: poll.v1.PollService.GetResults:output_type -> poll.v1.PollResults
	19, // 40: poll.v1.PollService.GetMyVote:output_type -> poll.v1.GetMyVoteResponse
	3,  // 41: poll.v1.PollService.ClosePoll:output_type -> poll.v1.Poll
	3,  // 42: poll.v1.PollService.ReopenPoll:output_type -> poll.v1.Poll
	23, // 43: poll.v1.PollService.GetPollInternal:output_type -> poll.v1.PollInternal
	32, // [32:44] is the sub-list for method output_type
	20, // [20:32] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_poll_proto_init() }
func file_poll_proto_init() {
	if File_poll_proto != nil {
		return
	}
	file_poll_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poll_proto_rawDesc), len(file_poll_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poll_proto_goTypes,
		DependencyIndexes: file_poll_proto_depIdxs,
		EnumInfos:         file_poll_proto_enumTypes,
		MessageInfos:      file_poll_proto_msgTypes,
	}.Build()
	File_poll_proto = out.File
	file_poll_proto_goTypes = nil
	file_poll_proto_depIdxs = nil
}
