run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - gosimple
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - revive
    - gci
    - gofmt

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/your-module)
    skip-generated: true
  gofmt:
    simplify: true
  errcheck:
    check-type-assertions: false
    check-blank: false
  gosec:
    excludes:
      - G104
  revive:
    ignore-generated-header: true
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  max-issues-per-linter: 50
  fix: false
