version: '2'
run:
  timeout: 5m
  tests: false
linters:
  enable:
    - errcheck
    - gosimple
    - gosec 
    - govet
    - ineffassign
    - staticcheck
    - revive
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - swaggo
issues:
  max-issues-per-linter: 50
  fix: false