// proto/chat/chat.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: chat.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionType int32

const (
	PermissionType_PERMISSION_UNKNOWN         PermissionType = 0
	PermissionType_PERMISSION_READ            PermissionType = 1 // Читать сообщения
	PermissionType_PERMISSION_WRITE           PermissionType = 2 // Отправлять сообщения
	PermissionType_PERMISSION_DELETE          PermissionType = 3 // Удалять сообщения
	PermissionType_PERMISSION_MANAGE_MEMBERS  PermissionType = 4 // Управлять участниками
	PermissionType_PERMISSION_UPDATE_SETTINGS PermissionType = 5 // Изменять настройки
)

// Enum value maps for PermissionType.
var (
	PermissionType_name = map[int32]string{
		0: "PERMISSION_UNKNOWN",
		1: "PERMISSION_READ",
		2: "PERMISSION_WRITE",
		3: "PERMISSION_DELETE",
		4: "PERMISSION_MANAGE_MEMBERS",
		5: "PERMISSION_UPDATE_SETTINGS",
	}
	PermissionType_value = map[string]int32{
		"PERMISSION_UNKNOWN":         0,
		"PERMISSION_READ":            1,
		"PERMISSION_WRITE":           2,
		"PERMISSION_DELETE":          3,
		"PERMISSION_MANAGE_MEMBERS":  4,
		"PERMISSION_UPDATE_SETTINGS": 5,
	}
)

func (x PermissionType) Enum() *PermissionType {
	p := new(PermissionType)
	*p = x
	return p
}

func (x PermissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (PermissionType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x PermissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionType.Descriptor instead.
func (PermissionType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

type ChatType int32

const (
	ChatType_CHAT_TYPE_UNKNOWN ChatType = 0
	ChatType_CHAT_TYPE_PRIVATE ChatType = 1 // Диалог 1-на-1
	ChatType_CHAT_TYPE_GROUP   ChatType = 2 // Групповой чат
	ChatType_CHAT_TYPE_CHANNEL ChatType = 3 // Канал (только вещание)
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "CHAT_TYPE_UNKNOWN",
		1: "CHAT_TYPE_PRIVATE",
		2: "CHAT_TYPE_GROUP",
		3: "CHAT_TYPE_CHANNEL",
	}
	ChatType_value = map[string]int32{
		"CHAT_TYPE_UNKNOWN": 0,
		"CHAT_TYPE_PRIVATE": 1,
		"CHAT_TYPE_GROUP":   2,
		"CHAT_TYPE_CHANNEL": 3,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[1].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[1]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

type Role int32

const (
	Role_ROLE_UNKNOWN   Role = 0
	Role_ROLE_MEMBER    Role = 1 // Обычный участник
	Role_ROLE_MODERATOR Role = 2 // Модератор (может удалять сообщения)
	Role_ROLE_ADMIN     Role = 3 // Администратор (управление чатом)
	Role_ROLE_OWNER     Role = 4 // Владелец (полный контроль)
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNKNOWN",
		1: "ROLE_MEMBER",
		2: "ROLE_MODERATOR",
		3: "ROLE_ADMIN",
		4: "ROLE_OWNER",
	}
	Role_value = map[string]int32{
		"ROLE_UNKNOWN":   0,
		"ROLE_MEMBER":    1,
		"ROLE_MODERATOR": 2,
		"ROLE_ADMIN":     3,
		"ROLE_OWNER":     4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[2].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[2]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

// Create Chat
type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                     // Название чата
	Type          ChatType               `protobuf:"varint,2,opt,name=type,proto3,enum=chat.v1.ChatType" json:"type,omitempty"`              // private/group/channel
	MemberIds     []string               `protobuf:"bytes,3,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`          // ID участников (включая создателя)
	AvatarBase64  string                 `protobuf:"bytes,4,opt,name=avatar_base64,json=avatarBase64,proto3" json:"avatar_base64,omitempty"` // Опционально: аватар чата
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatRequest) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_CHAT_TYPE_UNKNOWN
}

func (x *CreateChatRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *CreateChatRequest) GetAvatarBase64() string {
	if x != nil {
		return x.AvatarBase64
	}
	return ""
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          ChatType               `protobuf:"varint,3,opt,name=type,proto3,enum=chat.v1.ChatType" json:"type,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	MembersCount  int32                  `protobuf:"varint,6,opt,name=members_count,json=membersCount,proto3" json:"members_count,omitempty"`
	LastMessage   *Message               `protobuf:"bytes,7,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"` // Последнее сообщение (опционально)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chat) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_CHAT_TYPE_UNKNOWN
}

func (x *Chat) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Chat) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Chat) GetMembersCount() int32 {
	if x != nil {
		return x.MembersCount
	}
	return 0
}

func (x *Chat) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *Chat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chat) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Get Chat
type GetChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChatId         string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	IncludeMembers bool                   `protobuf:"varint,2,opt,name=include_members,json=includeMembers,proto3" json:"include_members,omitempty"` // Загрузить участников?
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetChatRequest) GetIncludeMembers() bool {
	if x != nil {
		return x.IncludeMembers
	}
	return false
}

// Get Chats (with pagination)
type GetChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *ChatFilter            `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsRequest) Reset() {
	*x = GetChatsRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsRequest) ProtoMessage() {}

func (x *GetChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsRequest.ProtoReflect.Descriptor instead.
func (*GetChatsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetChatsRequest) GetFilter() *ChatFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ChatFilter struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            ChatType               `protobuf:"varint,1,opt,name=type,proto3,enum=chat.v1.ChatType" json:"type,omitempty"`                        // Тип чата
	Search          string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`                                           // Поиск по названию
	ChatIds         []string               `protobuf:"bytes,3,rep,name=chat_ids,json=chatIds,proto3" json:"chat_ids,omitempty"`                          // Конкретные чаты
	IncludeArchived bool                   `protobuf:"varint,4,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"` // Включать архивные?
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatFilter) Reset() {
	*x = ChatFilter{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatFilter) ProtoMessage() {}

func (x *ChatFilter) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatFilter.ProtoReflect.Descriptor instead.
func (*ChatFilter) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ChatFilter) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_CHAT_TYPE_UNKNOWN
}

func (x *ChatFilter) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ChatFilter) GetChatIds() []string {
	if x != nil {
		return x.ChatIds
	}
	return nil
}

func (x *ChatFilter) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type GetChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsResponse) Reset() {
	*x = GetChatsResponse{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsResponse) ProtoMessage() {}

func (x *GetChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsResponse.ProtoReflect.Descriptor instead.
func (*GetChatsResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *GetChatsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Update Chat
type UpdateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	AvatarBase64  *string                `protobuf:"bytes,3,opt,name=avatar_base64,json=avatarBase64,proto3,oneof" json:"avatar_base64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatRequest) Reset() {
	*x = UpdateChatRequest{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatRequest) ProtoMessage() {}

func (x *UpdateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateChatRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateChatRequest) GetAvatarBase64() string {
	if x != nil && x.AvatarBase64 != nil {
		return *x.AvatarBase64
	}
	return ""
}

// Member Management
type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=chat.v1.Role" json:"role,omitempty"`         // По умолчанию MEMBER
	InvitedBy     string                 `protobuf:"bytes,4,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"` // Кто пригласил
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *AddMemberRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *AddMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMemberRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNKNOWN
}

func (x *AddMemberRequest) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveMemberRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Filter        *MemberFilter          `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GetMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetMembersRequest) GetFilter() *MemberFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type MemberFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=chat.v1.Role" json:"role,omitempty"` // Фильтр по роли
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`                // Поиск по имени
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberFilter) Reset() {
	*x = MemberFilter{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberFilter) ProtoMessage() {}

func (x *MemberFilter) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberFilter.ProtoReflect.Descriptor instead.
func (*MemberFilter) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *MemberFilter) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNKNOWN
}

func (x *MemberFilter) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *GetMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetMembersResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=chat.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateMemberRoleRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNKNOWN
}

type GetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{14}
}

func (x *GetMemberRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Member struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatId      string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Role        Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=chat.v1.Role" json:"role,omitempty"`
	JoinedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LastReadAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_read_at,json=lastReadAt,proto3" json:"last_read_at,omitempty"`
	UnreadCount int64                  `protobuf:"varint,6,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	// Данные пользователя (опционально, для REST)
	Username      string `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string `protobuf:"bytes,8,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AvatarUrl     string `protobuf:"bytes,9,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{15}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Member) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNKNOWN
}

func (x *Member) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *Member) GetLastReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReadAt
	}
	return nil
}

func (x *Member) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Member) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Member) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Member) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// Is Member (для других сервисов)
type IsMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberRequest) Reset() {
	*x = IsMemberRequest{}
	mi := &file_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberRequest) ProtoMessage() {}

func (x *IsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberRequest.ProtoReflect.Descriptor instead.
func (*IsMemberRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{16}
}

func (x *IsMemberRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *IsMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	Role          Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=chat.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberResponse) Reset() {
	*x = IsMemberResponse{}
	mi := &file_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberResponse) ProtoMessage() {}

func (x *IsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberResponse.ProtoReflect.Descriptor instead.
func (*IsMemberResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{17}
}

func (x *IsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *IsMemberResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNKNOWN
}

// Get User Chats
type GetUserChatsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IncludeLastMessage bool                   `protobuf:"varint,2,opt,name=include_last_message,json=includeLastMessage,proto3" json:"include_last_message,omitempty"` // Включить последнее сообщение?
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetUserChatsRequest) Reset() {
	*x = GetUserChatsRequest{}
	mi := &file_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserChatsRequest) ProtoMessage() {}

func (x *GetUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserChatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserChatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserChatsRequest) GetIncludeLastMessage() bool {
	if x != nil {
		return x.IncludeLastMessage
	}
	return false
}

type GetUserChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserChats     []*UserChat            `protobuf:"bytes,1,rep,name=user_chats,json=userChats,proto3" json:"user_chats,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserChatsResponse) Reset() {
	*x = GetUserChatsResponse{}
	mi := &file_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserChatsResponse) ProtoMessage() {}

func (x *GetUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserChatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserChatsResponse) GetUserChats() []*UserChat {
	if x != nil {
		return x.UserChats
	}
	return nil
}

func (x *GetUserChatsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UserChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	MemberInfo    *Member                `protobuf:"bytes,2,opt,name=member_info,json=memberInfo,proto3" json:"member_info,omitempty"`    // Информация о пользователе в чате
	LastMessage   *Message               `protobuf:"bytes,3,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"` // Последнее сообщение (опционально)
	UnreadCount   int64                  `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserChat) Reset() {
	*x = UserChat{}
	mi := &file_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChat) ProtoMessage() {}

func (x *UserChat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChat.ProtoReflect.Descriptor instead.
func (*UserChat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{20}
}

func (x *UserChat) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *UserChat) GetMemberInfo() *Member {
	if x != nil {
		return x.MemberInfo
	}
	return nil
}

func (x *UserChat) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *UserChat) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// Chat Settings
type UpdateChatSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Settings      *ChatSettings          `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatSettingsRequest) Reset() {
	*x = UpdateChatSettingsRequest{}
	mi := &file_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatSettingsRequest) ProtoMessage() {}

func (x *UpdateChatSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatSettingsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateChatSettingsRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateChatSettingsRequest) GetSettings() *ChatSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetChatSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatSettingsRequest) Reset() {
	*x = GetChatSettingsRequest{}
	mi := &file_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatSettingsRequest) ProtoMessage() {}

func (x *GetChatSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetChatSettingsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{22}
}

func (x *GetChatSettingsRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ChatSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IsPrivate            bool                   `protobuf:"varint,1,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`                                      // Закрытый чат (только по инвайту)
	AllowMessagesFromAll bool                   `protobuf:"varint,2,opt,name=allow_messages_from_all,json=allowMessagesFromAll,proto3" json:"allow_messages_from_all,omitempty"` // Могут писать все участники?
	AllowMedia           bool                   `protobuf:"varint,3,opt,name=allow_media,json=allowMedia,proto3" json:"allow_media,omitempty"`                                   // Разрешены медиафайлы?
	AllowReactions       bool                   `protobuf:"varint,4,opt,name=allow_reactions,json=allowReactions,proto3" json:"allow_reactions,omitempty"`                       // Разрешены реакции?
	MessageTtlSeconds    int32                  `protobuf:"varint,5,opt,name=message_ttl_seconds,json=messageTtlSeconds,proto3" json:"message_ttl_seconds,omitempty"`            // Автоудаление сообщений (0 = без удаления)
	Language             string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`                                                          // Язык чата (для переводов)
	IsAnnouncement       bool                   `protobuf:"varint,7,opt,name=is_announcement,json=isAnnouncement,proto3" json:"is_announcement,omitempty"`                       // Только админы могут писать?
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChatSettings) Reset() {
	*x = ChatSettings{}
	mi := &file_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSettings) ProtoMessage() {}

func (x *ChatSettings) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSettings.ProtoReflect.Descriptor instead.
func (*ChatSettings) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{23}
}

func (x *ChatSettings) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *ChatSettings) GetAllowMessagesFromAll() bool {
	if x != nil {
		return x.AllowMessagesFromAll
	}
	return false
}

func (x *ChatSettings) GetAllowMedia() bool {
	if x != nil {
		return x.AllowMedia
	}
	return false
}

func (x *ChatSettings) GetAllowReactions() bool {
	if x != nil {
		return x.AllowReactions
	}
	return false
}

func (x *ChatSettings) GetMessageTtlSeconds() int32 {
	if x != nil {
		return x.MessageTtlSeconds
	}
	return 0
}

func (x *ChatSettings) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ChatSettings) GetIsAnnouncement() bool {
	if x != nil {
		return x.IsAnnouncement
	}
	return false
}

// Invite Links
type CreateInviteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MaxUses       int32                  `protobuf:"varint,2,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`      // Максимум использований (0 = без лимита)
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Когда истекает
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteLinkRequest) Reset() {
	*x = CreateInviteLinkRequest{}
	mi := &file_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteLinkRequest) ProtoMessage() {}

func (x *CreateInviteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteLinkRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{24}
}

func (x *CreateInviteLinkRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CreateInviteLinkRequest) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *CreateInviteLinkRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type InviteLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"` // Короткий код для ссылки
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`   // Полная ссылка
	MaxUses       int32                  `protobuf:"varint,5,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UsedCount     int32                  `protobuf:"varint,6,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	IsActive      bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteLink) Reset() {
	*x = InviteLink{}
	mi := &file_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteLink) ProtoMessage() {}

func (x *InviteLink) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteLink.ProtoReflect.Descriptor instead.
func (*InviteLink) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{25}
}

func (x *InviteLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InviteLink) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *InviteLink) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InviteLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *InviteLink) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *InviteLink) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *InviteLink) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *InviteLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InviteLink) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *InviteLink) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type JoinChatByInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Из контекста
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChatByInviteRequest) Reset() {
	*x = JoinChatByInviteRequest{}
	mi := &file_chat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChatByInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChatByInviteRequest) ProtoMessage() {}

func (x *JoinChatByInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChatByInviteRequest.ProtoReflect.Descriptor instead.
func (*JoinChatByInviteRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{26}
}

func (x *JoinChatByInviteRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *JoinChatByInviteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RevokeInviteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	InviteId      string                 `protobuf:"bytes,2,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInviteLinkRequest) Reset() {
	*x = RevokeInviteLinkRequest{}
	mi := &file_chat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInviteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInviteLinkRequest) ProtoMessage() {}

func (x *RevokeInviteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInviteLinkRequest.ProtoReflect.Descriptor instead.
func (*RevokeInviteLinkRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{27}
}

func (x *RevokeInviteLinkRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RevokeInviteLinkRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

// Internal Messages (для других сервисов)
type GetChatInternalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChatId         string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	IncludeMembers bool                   `protobuf:"varint,2,opt,name=include_members,json=includeMembers,proto3" json:"include_members,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetChatInternalRequest) Reset() {
	*x = GetChatInternalRequest{}
	mi := &file_chat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatInternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatInternalRequest) ProtoMessage() {}

func (x *GetChatInternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatInternalRequest.ProtoReflect.Descriptor instead.
func (*GetChatInternalRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{28}
}

func (x *GetChatInternalRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetChatInternalRequest) GetIncludeMembers() bool {
	if x != nil {
		return x.IncludeMembers
	}
	return false
}

type ChatInternal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          ChatType               `protobuf:"varint,3,opt,name=type,proto3,enum=chat.v1.ChatType" json:"type,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	MemberIds     []string               `protobuf:"bytes,5,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"` // Список ID участников
	Settings      *ChatSettings          `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInternal) Reset() {
	*x = ChatInternal{}
	mi := &file_chat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInternal) ProtoMessage() {}

func (x *ChatInternal) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInternal.ProtoReflect.Descriptor instead.
func (*ChatInternal) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{29}
}

func (x *ChatInternal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatInternal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatInternal) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_CHAT_TYPE_UNKNOWN
}

func (x *ChatInternal) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ChatInternal) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *ChatInternal) GetSettings() *ChatSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetChatsInternalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatIds       []string               `protobuf:"bytes,1,rep,name=chat_ids,json=chatIds,proto3" json:"chat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsInternalRequest) Reset() {
	*x = GetChatsInternalRequest{}
	mi := &file_chat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsInternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsInternalRequest) ProtoMessage() {}

func (x *GetChatsInternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsInternalRequest.ProtoReflect.Descriptor instead.
func (*GetChatsInternalRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{30}
}

func (x *GetChatsInternalRequest) GetChatIds() []string {
	if x != nil {
		return x.ChatIds
	}
	return nil
}

type GetChatsInternalResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Chats         map[string]*ChatInternal `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // chat_id -> ChatInternal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsInternalResponse) Reset() {
	*x = GetChatsInternalResponse{}
	mi := &file_chat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsInternalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsInternalResponse) ProtoMessage() {}

func (x *GetChatsInternalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsInternalResponse.ProtoReflect.Descriptor instead.
func (*GetChatsInternalResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{31}
}

func (x *GetChatsInternalResponse) GetChats() map[string]*ChatInternal {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ValidateMemberAccessRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChatId             string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequiredPermission PermissionType         `protobuf:"varint,3,opt,name=required_permission,json=requiredPermission,proto3,enum=chat.v1.PermissionType" json:"required_permission,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidateMemberAccessRequest) Reset() {
	*x = ValidateMemberAccessRequest{}
	mi := &file_chat_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMemberAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMemberAccessRequest) ProtoMessage() {}

func (x *ValidateMemberAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMemberAccessRequest.ProtoReflect.Descriptor instead.
func (*ValidateMemberAccessRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{32}
}

func (x *ValidateMemberAccessRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ValidateMemberAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateMemberAccessRequest) GetRequiredPermission() PermissionType {
	if x != nil {
		return x.RequiredPermission
	}
	return PermissionType_PERMISSION_UNKNOWN
}

type ValidateMemberAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	Role          Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=chat.v1.Role" json:"role,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // Если нет доступа, причина
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMemberAccessResponse) Reset() {
	*x = ValidateMemberAccessResponse{}
	mi := &file_chat_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMemberAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMemberAccessResponse) ProtoMessage() {}

func (x *ValidateMemberAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMemberAccessResponse.ProtoReflect.Descriptor instead.
func (*ValidateMemberAccessResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{33}
}

func (x *ValidateMemberAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *ValidateMemberAccessResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNKNOWN
}

func (x *ValidateMemberAccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Last Read
type UpdateLastReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Последнее прочитанное сообщение
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastReadRequest) Reset() {
	*x = UpdateLastReadRequest{}
	mi := &file_chat_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastReadRequest) ProtoMessage() {}

func (x *UpdateLastReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastReadRequest.ProtoReflect.Descriptor instead.
func (*UpdateLastReadRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{34}
}

func (x *UpdateLastReadRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateLastReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLastReadRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// Message (ссылка на Message Service)
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Минимальная информация, полное сообщение в Message Service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chat_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{35}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\achat.v1\x1a\x0ftimestamp.proto\"\a\n" +
	"\x05Empty\"\x92\x01\n" +
	"\x11CreateChatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.chat.v1.ChatTypeR\x04type\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\tR\tmemberIds\x12#\n" +
	"\ravatar_base64\x18\x04 \x01(\tR\favatarBase64\"\xdf\x02\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.chat.v1.ChatTypeR\x04type\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12#\n" +
	"\rmembers_count\x18\x06 \x01(\x05R\fmembersCount\x123\n" +
	"\flast_message\x18\a \x01(\v2\x10.chat.v1.MessageR\vlastMessage\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"R\n" +
	"\x0eGetChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12'\n" +
	"\x0finclude_members\x18\x02 \x01(\bR\x0eincludeMembers\">\n" +
	"\x0fGetChatsRequest\x12+\n" +
	"\x06filter\x18\x01 \x01(\v2\x13.chat.v1.ChatFilterR\x06filter\"\x91\x01\n" +
	"\n" +
	"ChatFilter\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.chat.v1.ChatTypeR\x04type\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x19\n" +
	"\bchat_ids\x18\x03 \x03(\tR\achatIds\x12)\n" +
	"\x10include_archived\x18\x04 \x01(\bR\x0fincludeArchived\"X\n" +
	"\x10GetChatsResponse\x12#\n" +
	"\x05chats\x18\x01 \x03(\v2\r.chat.v1.ChatR\x05chats\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\x8a\x01\n" +
	"\x11UpdateChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12(\n" +
	"\ravatar_base64\x18\x03 \x01(\tH\x01R\favatarBase64\x88\x01\x01B\a\n" +
	"\x05_nameB\x10\n" +
	"\x0e_avatar_base64\"\x86\x01\n" +
	"\x10AddMemberRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\x04role\x18\x03 \x01(\x0e2\r.chat.v1.RoleR\x04role\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x04 \x01(\tR\tinvitedBy\"G\n" +
	"\x13RemoveMemberRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"[\n" +
	"\x11GetMembersRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12-\n" +
	"\x06filter\x18\x02 \x01(\v2\x15.chat.v1.MemberFilterR\x06filter\"I\n" +
	"\fMemberFilter\x12!\n" +
	"\x04role\x18\x01 \x01(\x0e2\r.chat.v1.RoleR\x04role\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\"`\n" +
	"\x12GetMembersResponse\x12)\n" +
	"\amembers\x18\x01 \x03(\v2\x0f.chat.v1.MemberR\amembers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"n\n" +
	"\x17UpdateMemberRoleRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\x04role\x18\x03 \x01(\x0e2\r.chat.v1.RoleR\x04role\"D\n" +
	"\x10GetMemberRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xcf\x02\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12!\n" +
	"\x04role\x18\x03 \x01(\x0e2\r.chat.v1.RoleR\x04role\x127\n" +
	"\tjoined_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12<\n" +
	"\flast_read_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastReadAt\x12!\n" +
	"\funread_count\x18\x06 \x01(\x03R\vunreadCount\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\b \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\t \x01(\tR\tavatarUrl\"C\n" +
	"\x0fIsMemberRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"R\n" +
	"\x10IsMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\x12!\n" +
	"\x04role\x18\x02 \x01(\x0e2\r.chat.v1.RoleR\x04role\"`\n" +
	"\x13GetUserChatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x14include_last_message\x18\x02 \x01(\bR\x12includeLastMessage\"i\n" +
	"\x14GetUserChatsResponse\x120\n" +
	"\n" +
	"user_chats\x18\x01 \x03(\v2\x11.chat.v1.UserChatR\tuserChats\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xb7\x01\n" +
	"\bUserChat\x12!\n" +
	"\x04chat\x18\x01 \x01(\v2\r.chat.v1.ChatR\x04chat\x120\n" +
	"\vmember_info\x18\x02 \x01(\v2\x0f.chat.v1.MemberR\n" +
	"memberInfo\x123\n" +
	"\flast_message\x18\x03 \x01(\v2\x10.chat.v1.MessageR\vlastMessage\x12!\n" +
	"\funread_count\x18\x04 \x01(\x03R\vunreadCount\"g\n" +
	"\x19UpdateChatSettingsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x121\n" +
	"\bsettings\x18\x02 \x01(\v2\x15.chat.v1.ChatSettingsR\bsettings\"1\n" +
	"\x16GetChatSettingsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\xa3\x02\n" +
	"\fChatSettings\x12\x1d\n" +
	"\n" +
	"is_private\x18\x01 \x01(\bR\tisPrivate\x125\n" +
	"\x17allow_messages_from_all\x18\x02 \x01(\bR\x14allowMessagesFromAll\x12\x1f\n" +
	"\vallow_media\x18\x03 \x01(\bR\n" +
	"allowMedia\x12'\n" +
	"\x0fallow_reactions\x18\x04 \x01(\bR\x0eallowReactions\x12.\n" +
	"\x13message_ttl_seconds\x18\x05 \x01(\x05R\x11messageTtlSeconds\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12'\n" +
	"\x0fis_announcement\x18\a \x01(\bR\x0eisAnnouncement\"\x88\x01\n" +
	"\x17CreateInviteLinkRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x19\n" +
	"\bmax_uses\x18\x02 \x01(\x05R\amaxUses\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xc7\x02\n" +
	"\n" +
	"InviteLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x19\n" +
	"\bmax_uses\x18\x05 \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"used_count\x18\x06 \x01(\x05R\tusedCount\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\"S\n" +
	"\x17JoinChatByInviteRequest\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"O\n" +
	"\x17RevokeInviteLinkRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tinvite_id\x18\x02 \x01(\tR\binviteId\"Z\n" +
	"\x16GetChatInternalRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12'\n" +
	"\x0finclude_members\x18\x02 \x01(\bR\x0eincludeMembers\"\xc8\x01\n" +
	"\fChatInternal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.chat.v1.ChatTypeR\x04type\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x05 \x03(\tR\tmemberIds\x121\n" +
	"\bsettings\x18\x06 \x01(\v2\x15.chat.v1.ChatSettingsR\bsettings\"4\n" +
	"\x17GetChatsInternalRequest\x12\x19\n" +
	"\bchat_ids\x18\x01 \x03(\tR\achatIds\"\xaf\x01\n" +
	"\x18GetChatsInternalResponse\x12B\n" +
	"\x05chats\x18\x01 \x03(\v2,.chat.v1.GetChatsInternalResponse.ChatsEntryR\x05chats\x1aO\n" +
	"\n" +
	"ChatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.chat.v1.ChatInternalR\x05value:\x028\x01\"\x99\x01\n" +
	"\x1bValidateMemberAccessRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12H\n" +
	"\x13required_permission\x18\x03 \x01(\x0e2\x17.chat.v1.PermissionTypeR\x12requiredPermission\"x\n" +
	"\x1cValidateMemberAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\x12!\n" +
	"\x04role\x18\x02 \x01(\x0e2\r.chat.v1.RoleR\x04role\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"h\n" +
	"\x15UpdateLastReadRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"\xa4\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*\xa9\x01\n" +
	"\x0ePermissionType\x12\x16\n" +
	"\x12PERMISSION_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fPERMISSION_READ\x10\x01\x12\x14\n" +
	"\x10PERMISSION_WRITE\x10\x02\x12\x15\n" +
	"\x11PERMISSION_DELETE\x10\x03\x12\x1d\n" +
	"\x19PERMISSION_MANAGE_MEMBERS\x10\x04\x12\x1e\n" +
	"\x1aPERMISSION_UPDATE_SETTINGS\x10\x05*d\n" +
	"\bChatType\x12\x15\n" +
	"\x11CHAT_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CHAT_TYPE_PRIVATE\x10\x01\x12\x13\n" +
	"\x0fCHAT_TYPE_GROUP\x10\x02\x12\x15\n" +
	"\x11CHAT_TYPE_CHANNEL\x10\x03*]\n" +
	"\x04Role\x12\x10\n" +
	"\fROLE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vROLE_MEMBER\x10\x01\x12\x12\n" +
	"\x0eROLE_MODERATOR\x10\x02\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x03\x12\x0e\n" +
	"\n" +
	"ROLE_OWNER\x10\x042\xa4\t\n" +
	"\vChatService\x127\n" +
	"\n" +
	"CreateChat\x12\x1a.chat.v1.CreateChatRequest\x1a\r.chat.v1.Chat\x121\n" +
	"\aGetChat\x12\x17.chat.v1.GetChatRequest\x1a\r.chat.v1.Chat\x12?\n" +
	"\bGetChats\x12\x18.chat.v1.GetChatsRequest\x1a\x19.chat.v1.GetChatsResponse\x127\n" +
	"\n" +
	"UpdateChat\x12\x1a.chat.v1.UpdateChatRequest\x1a\r.chat.v1.Chat\x127\n" +
	"\tAddMember\x12\x19.chat.v1.AddMemberRequest\x1a\x0f.chat.v1.Member\x12<\n" +
	"\fRemoveMember\x12\x1c.chat.v1.RemoveMemberRequest\x1a\x0e.chat.v1.Empty\x12E\n" +
	"\n" +
	"GetMembers\x12\x1a.chat.v1.GetMembersRequest\x1a\x1b.chat.v1.GetMembersResponse\x12E\n" +
	"\x10UpdateMemberRole\x12 .chat.v1.UpdateMemberRoleRequest\x1a\x0f.chat.v1.Member\x127\n" +
	"\tGetMember\x12\x19.chat.v1.GetMemberRequest\x1a\x0f.chat.v1.Member\x12?\n" +
	"\bIsMember\x12\x18.chat.v1.IsMemberRequest\x1a\x19.chat.v1.IsMemberResponse\x12K\n" +
	"\fGetUserChats\x12\x1c.chat.v1.GetUserChatsRequest\x1a\x1d.chat.v1.GetUserChatsResponse\x12I\n" +
	"\x10CreateInviteLink\x12 .chat.v1.CreateInviteLinkRequest\x1a\x13.chat.v1.InviteLink\x12C\n" +
	"\x10JoinChatByInvite\x12 .chat.v1.JoinChatByInviteRequest\x1a\r.chat.v1.Chat\x12D\n" +
	"\x10RevokeInviteLink\x12 .chat.v1.RevokeInviteLinkRequest\x1a\x0e.chat.v1.Empty\x12K\n" +
	"\x0fGetChatInternal\x12\x1f.chat.v1.GetChatInternalRequest\x1a\x15.chat.v1.ChatInternal\"\x00\x12Y\n" +
	"\x10GetChatsInternal\x12 .chat.v1.GetChatsInternalRequest\x1a!.chat.v1.GetChatsInternalResponse\"\x00\x12e\n" +
	"\x14ValidateMemberAccess\x12$.chat.v1.ValidateMemberAccessRequest\x1a%.chat.v1.ValidateMemberAccessResponse\"\x00B?Z=github.com/north-fy/talker/services/chat/pkg/protos/v1;chatv1b\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_chat_proto_goTypes = []any{
	(PermissionType)(0),                  // 0: chat.v1.PermissionType
	(ChatType)(0),                        // 1: chat.v1.ChatType
	(Role)(0),                            // 2: chat.v1.Role
	(*Empty)(nil),                        // 3: chat.v1.Empty
	(*CreateChatRequest)(nil),            // 4: chat.v1.CreateChatRequest
	(*Chat)(nil),                         // 5: chat.v1.Chat
	(*GetChatRequest)(nil),               // 6: chat.v1.GetChatRequest
	(*GetChatsRequest)(nil),              // 7: chat.v1.GetChatsRequest
	(*ChatFilter)(nil),                   // 8: chat.v1.ChatFilter
	(*GetChatsResponse)(nil),             // 9: chat.v1.GetChatsResponse
	(*UpdateChatRequest)(nil),            // 10: chat.v1.UpdateChatRequest
	(*AddMemberRequest)(nil),             // 11: chat.v1.AddMemberRequest
	(*RemoveMemberRequest)(nil),          // 12: chat.v1.RemoveMemberRequest
	(*GetMembersRequest)(nil),            // 13: chat.v1.GetMembersRequest
	(*MemberFilter)(nil),                 // 14: chat.v1.MemberFilter
	(*GetMembersResponse)(nil),           // 15: chat.v1.GetMembersResponse
	(*UpdateMemberRoleRequest)(nil),      // 16: chat.v1.UpdateMemberRoleRequest
	(*GetMemberRequest)(nil),             // 17: chat.v1.GetMemberRequest
	(*Member)(nil),                       // 18: chat.v1.Member
	(*IsMemberRequest)(nil),              // 19: chat.v1.IsMemberRequest
	(*IsMemberResponse)(nil),             // 20: chat.v1.IsMemberResponse
	(*GetUserChatsRequest)(nil),          // 21: chat.v1.GetUserChatsRequest
	(*GetUserChatsResponse)(nil),         // 22: chat.v1.GetUserChatsResponse
	(*UserChat)(nil),                     // 23: chat.v1.UserChat
	(*UpdateChatSettingsRequest)(nil),    // 24: chat.v1.UpdateChatSettingsRequest
	(*GetChatSettingsRequest)(nil),       // 25: chat.v1.GetChatSettingsRequest
	(*ChatSettings)(nil),                 // 26: chat.v1.ChatSettings
	(*CreateInviteLinkRequest)(nil),      // 27: chat.v1.CreateInviteLinkRequest
	(*InviteLink)(nil),                   // 28: chat.v1.InviteLink
	(*JoinChatByInviteRequest)(nil),      // 29: chat.v1.JoinChatByInviteRequest
	(*RevokeInviteLinkRequest)(nil),      // 30: chat.v1.RevokeInviteLinkRequest
	(*GetChatInternalRequest)(nil),       // 31: chat.v1.GetChatInternalRequest
	(*ChatInternal)(nil),                 // 32: chat.v1.ChatInternal
	(*GetChatsInternalRequest)(nil),      // 33: chat.v1.GetChatsInternalRequest
	(*GetChatsInternalResponse)(nil),     // 34: chat.v1.GetChatsInternalResponse
	(*ValidateMemberAccessRequest)(nil),  // 35: chat.v1.ValidateMemberAccessRequest
	(*ValidateMemberAccessResponse)(nil), // 36: chat.v1.ValidateMemberAccessResponse
	(*UpdateLastReadRequest)(nil),        // 37: chat.v1.UpdateLastReadRequest
	(*Message)(nil),                      // 38: chat.v1.Message
	nil,                                  // 39: chat.v1.GetChatsInternalResponse.ChatsEntry
	(*timestamppb.Timestamp)(nil),        // 40: google.protobuf.Timestamp
}
var file_chat_proto_depIdxs = []int32{
	1,  // 0: chat.v1.CreateChatRequest.type:type_name -> chat.v1.ChatType
	1,  // 1: chat.v1.Chat.type:type_name -> chat.v1.ChatType
	38, // 2: chat.v1.Chat.last_message:type_name -> chat.v1.Message
	40, // 3: chat.v1.Chat.created_at:type_name -> google.protobuf.Timestamp
	40, // 4: chat.v1.Chat.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 5: chat.v1.GetChatsRequest.filter:type_name -> chat.v1.ChatFilter
	1,  // 6: chat.v1.ChatFilter.type:type_name -> chat.v1.ChatType
	5,  // 7: chat.v1.GetChatsResponse.chats:type_name -> chat.v1.Chat
	2,  // 8: chat.v1.AddMemberRequest.role:type_name -> chat.v1.Role
	14, // 9: chat.v1.GetMembersRequest.filter:type_name -> chat.v1.MemberFilter
	2,  // 10: chat.v1.MemberFilter.role:type_name -> chat.v1.Role
	18, // 11: chat.v1.GetMembersResponse.members:type_name -> chat.v1.Member
	2,  // 12: chat.v1.UpdateMemberRoleRequest.role:type_name -> chat.v1.Role
	2,  // 13: chat.v1.Member.role:type_name -> chat.v1.Role
	40, // 14: chat.v1.Member.joined_at:type_name -> google.protobuf.Timestamp
	40, // 15: chat.v1.Member.last_read_at:type_name -> google.protobuf.Timestamp
	2,  // 16: chat.v1.IsMemberResponse.role:type_name -> chat.v1.Role
	23, // 17: chat.v1.GetUserChatsResponse.user_chats:type_name -> chat.v1.UserChat
	5,  // 18: chat.v1.UserChat.chat:type_name -> chat.v1.Chat
	18, // 19: chat.v1.UserChat.member_info:type_name -> chat.v1.Member
	38, // 20: chat.v1.UserChat.last_message:type_name -> chat.v1.Message
	26, // 21: chat.v1.UpdateChatSettingsRequest.settings:type_name -> chat.v1.ChatSettings
	40, // 22: chat.v1.CreateInviteLinkRequest.expires_at:type_name -> google.protobuf.Timestamp
	40, // 23: chat.v1.InviteLink.expires_at:type_name -> google.protobuf.Timestamp
	40, // 24: chat.v1.InviteLink.created_at:type_name -> google.protobuf.Timestamp
	1,  // 25: chat.v1.ChatInternal.type:type_name -> chat.v1.ChatType
	26, // 26: chat.v1.ChatInternal.settings:type_name -> chat.v1.ChatSettings
	39, // 27: chat.v1.GetChatsInternalResponse.chats:type_name -> chat.v1.GetChatsInternalResponse.ChatsEntry
	0,  // 28: chat.v1.ValidateMemberAccessRequest.required_permission:type_name -> chat.v1.PermissionType
	2,  // 29: chat.v1.ValidateMemberAccessResponse.role:type_name -> chat.v1.Role
	40, // 30: chat.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	32, // 31: chat.v1.GetChatsInternalResponse.ChatsEntry.value:type_name -> chat.v1.ChatInternal
	4,  // 32: chat.v1.ChatService.CreateChat:input_type -> chat.v1.CreateChatRequest
	6,  // 33: chat.v1.ChatService.GetChat:input_type -> chat.v1.GetChatRequest
	7,  // 34: chat.v1.ChatService.GetChats:input_type -> chat.v1.GetChatsRequest
	10, // 35: chat.v1.ChatService.UpdateChat:input_type -> chat.v1.UpdateChatRequest
	11, // 36: chat.v1.ChatService.AddMember:input_type -> chat.v1.AddMemberRequest
	12, // 37: chat.v1.ChatService.RemoveMember:input_type -> chat.v1.RemoveMemberRequest
	13, // 38: chat.v1.ChatService.GetMembers:input_type -> chat.v1.GetMembersRequest
	16, // 39: chat.v1.ChatService.UpdateMemberRole:input_type -> chat.v1.UpdateMemberRoleRequest
	17, // 40: chat.v1.ChatService.GetMember:input_type -> chat.v1.GetMemberRequest
	19, // 41: chat.v1.ChatService.IsMember:input_type -> chat.v1.IsMemberRequest
	21, // 42: chat.v1.ChatService.GetUserChats:input_type -> chat.v1.GetUserChatsRequest
	27, // 43: chat.v1.ChatService.CreateInviteLink:input_type -> chat.v1.CreateInviteLinkRequest
	29, // 44: chat.v1.ChatService.JoinChatByInvite:input_type -> chat.v1.JoinChatByInviteRequest
	30, // 45: chat.v1.ChatService.RevokeInviteLink:input_type -> chat.v1.RevokeInviteLinkRequest
	31, // 46: chat.v1.ChatService.GetChatInternal:input_type -> chat.v1.GetChatInternalRequest
	33, // 47: chat.v1.ChatService.GetChatsInternal:input_type -> chat.v1.GetChatsInternalRequest
	35, // 48: chat.v1.ChatService.ValidateMemberAccess:input_type -> chat.v1.ValidateMemberAccessRequest
	5,  // 49: chat.v1.ChatService.CreateChat:output_type -> chat.v1.Chat
	5,  // 50: chat.v1.ChatService.GetChat:output_type -> chat.v1.Chat
	9,  // 51: chat.v1.ChatService.GetChats:output_type -> chat.v1.GetChatsResponse
	5,  // 52: chat.v1.ChatService.UpdateChat:output_type -> chat.v1.Chat
	18, // 53: chat.v1.ChatService.AddMember:output_type -> chat.v1.Member
	3,  // 54: chat.v1.ChatService.RemoveMember:output_type -> chat.v1.Empty
	15, // 55: chat.v1.ChatService.GetMembers:output_type -> chat.v1.GetMembersResponse
	18, // 56: chat.v1.ChatService.UpdateMemberRole:output_type -> chat.v1.Member
	18, // 57: chat.v1.ChatService.GetMember:output_type -> chat.v1.Member
	20, // 58: chat.v1.ChatService.IsMember:output_type -> chat.v1.IsMemberResponse
	22, // 59: chat.v1.ChatService.GetUserChats:output_type -> chat.v1.GetUserChatsResponse
	28, // 60: chat.v1.ChatService.CreateInviteLink:output_type -> chat.v1.InviteLink
	5,  // 61: chat.v1.ChatService.JoinChatByInvite:output_type -> chat.v1.Chat
	3,  // 62: chat.v1.ChatService.RevokeInviteLink:output_type -> chat.v1.Empty
	32, // 63: chat.v1.ChatService.GetChatInternal:output_type -> chat.v1.ChatInternal
	34, // 64: chat.v1.ChatService.GetChatsInternal:output_type -> chat.v1.GetChatsInternalResponse
	36, // 65: chat.v1.ChatService.ValidateMemberAccess:output_type -> chat.v1.ValidateMemberAccessResponse
	49, // [49:66] is the sub-list for method output_type
	32, // [32:49] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_chat_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
