apiVersion: v1
data:
  000001_create_user_table.down.sql: DROP TABLE users;
  000001_create_user_table.up.sql: |-
    CREATE TABLE users (
        id BIGSERIAL PRIMARY KEY,
        first_name VARCHAR(255) NOT NULL,
        last_name VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
    )
  000002_add_username.down.sql: ALTER TABLE users DROP COLUMN username;
  000002_add_username.up.sql: ALTER TABLE users ADD COLUMN username VARCHAR(100);
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: migrate
  name: migrate-cm0
