version: '3'

services:
  postgres:
    image: postgres:16-alpine
    container_name: chat-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chat-network

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - up
    networks:
      - chat-network

  redis:
    image: redis:8.8-alpine
    container_name: chat-redis
    command: redis-server --requirepass redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chat-network

  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      GRPC_PORT: 50053
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      REDIS_READ_TIMEOUT: 30s
      REDIS_WRITE_TIMEOUT: 30s
      REDIS_DB: 0
      USER_SRV_ADDR: host.docker.internal:50051
      MESSAGE_SRV_ADDR: host.docker.internal:50052
    ports:
      - "50053:50053"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - chat-network

volumes:
  postgres_data:
  redis_data:

networks:
  chat-network:
    driver: bridge
