// proto/message/message.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: message.proto

package messagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Типы сообщений
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNKNOWN MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT    MessageType = 1 // Обычный текст
	MessageType_MESSAGE_TYPE_IMAGE   MessageType = 2 // Изображение
	MessageType_MESSAGE_TYPE_FILE    MessageType = 3 // Файл
	MessageType_MESSAGE_TYPE_STICKER MessageType = 4 // Стикер
	MessageType_MESSAGE_TYPE_SYSTEM  MessageType = 5 // Системное сообщение (user joined, etc)
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNKNOWN",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_IMAGE",
		3: "MESSAGE_TYPE_FILE",
		4: "MESSAGE_TYPE_STICKER",
		5: "MESSAGE_TYPE_SYSTEM",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNKNOWN": 0,
		"MESSAGE_TYPE_TEXT":    1,
		"MESSAGE_TYPE_IMAGE":   2,
		"MESSAGE_TYPE_FILE":    3,
		"MESSAGE_TYPE_STICKER": 4,
		"MESSAGE_TYPE_SYSTEM":  5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

// Отправка сообщения
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`           // ID чата
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                        // Текст сообщения
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=message.v1.MessageType" json:"type,omitempty"` // Тип сообщения (text, image, file)
	ReplyTo       int64                  `protobuf:"varint,4,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`        // ID сообщения, на которое отвечаем (опционально)
	Attachments   []int64                `protobuf:"varint,5,rep,packed,name=attachments,proto3" json:"attachments,omitempty"`        // Список ID вложений (из File Service)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *SendMessageRequest) GetReplyTo() int64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

func (x *SendMessageRequest) GetAttachments() []int64 {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// Получение сообщений чата
type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"` // ID чата
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                 // Сколько сообщений (max 100)
	Before        int64                  `protobuf:"varint,3,opt,name=before,proto3" json:"before,omitempty"`               // Пагинация: ID сообщения, до которого грузить
	After         int64                  `protobuf:"varint,4,opt,name=after,proto3" json:"after,omitempty"`                 // Пагинация: ID сообщения, после которого грузить
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesRequest) GetBefore() int64 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *GetMessagesRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`          // Есть ли ещё сообщения
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Общее количество (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetMessagesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Редактирование сообщения
type EditMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Новый текст
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageRequest) Reset() {
	*x = EditMessageRequest{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageRequest) ProtoMessage() {}

func (x *EditMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageRequest.ProtoReflect.Descriptor instead.
func (*EditMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *EditMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *EditMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Удаление сообщения
type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ForEveryone   bool                   `protobuf:"varint,2,opt,name=for_everyone,json=forEveryone,proto3" json:"for_everyone,omitempty"` // Удалить у всех (true) или только у себя (false)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *DeleteMessageRequest) GetForEveryone() bool {
	if x != nil {
		return x.ForEveryone
	}
	return false
}

// Получить одно сообщение
type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// Реакции
type AddReactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Reaction      string                 `protobuf:"bytes,2,opt,name=reaction,proto3" json:"reaction,omitempty"` // Смайлик: "❤️", "👍", "😂" и т.д.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReactionRequest) Reset() {
	*x = AddReactionRequest{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReactionRequest) ProtoMessage() {}

func (x *AddReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReactionRequest.ProtoReflect.Descriptor instead.
func (*AddReactionRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *AddReactionRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *AddReactionRequest) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

type RemoveReactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Reaction      string                 `protobuf:"bytes,2,opt,name=reaction,proto3" json:"reaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReactionRequest) Reset() {
	*x = RemoveReactionRequest{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReactionRequest) ProtoMessage() {}

func (x *RemoveReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReactionRequest.ProtoReflect.Descriptor instead.
func (*RemoveReactionRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveReactionRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *RemoveReactionRequest) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

type GetReactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReactionsRequest) Reset() {
	*x = GetReactionsRequest{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionsRequest) ProtoMessage() {}

func (x *GetReactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionsRequest.ProtoReflect.Descriptor instead.
func (*GetReactionsRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetReactionsRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type GetReactionsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Reactions     map[string]*ReactionCount `protobuf:"bytes,1,rep,name=reactions,proto3" json:"reactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // reaction -> количество
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReactionsResponse) Reset() {
	*x = GetReactionsResponse{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionsResponse) ProtoMessage() {}

func (x *GetReactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionsResponse.ProtoReflect.Descriptor instead.
func (*GetReactionsResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *GetReactionsResponse) GetReactions() map[string]*ReactionCount {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type ReactionCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reaction      string                 `protobuf:"bytes,1,opt,name=reaction,proto3" json:"reaction,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	UserIds       []int64                `protobuf:"varint,3,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // Кто поставил (первые 10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionCount) Reset() {
	*x = ReactionCount{}
	mi := &file_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionCount) ProtoMessage() {}

func (x *ReactionCount) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionCount.ProtoReflect.Descriptor instead.
func (*ReactionCount) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *ReactionCount) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

func (x *ReactionCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReactionCount) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// Поиск сообщений
type SearchMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"` // Опционально: поиск только в конкретном чате
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                  // Поисковый запрос
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                 // Максимум результатов (max 50)
	Before        int64                  `protobuf:"varint,4,opt,name=before,proto3" json:"before,omitempty"`               // Пагинация
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessagesRequest) Reset() {
	*x = SearchMessagesRequest{}
	mi := &file_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesRequest) ProtoMessage() {}

func (x *SearchMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesRequest.ProtoReflect.Descriptor instead.
func (*SearchMessagesRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{12}
}

func (x *SearchMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SearchMessagesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchMessagesRequest) GetBefore() int64 {
	if x != nil {
		return x.Before
	}
	return 0
}

type SearchMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessagesResponse) Reset() {
	*x = SearchMessagesResponse{}
	mi := &file_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesResponse) ProtoMessage() {}

func (x *SearchMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesResponse.ProtoReflect.Descriptor instead.
func (*SearchMessagesResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{13}
}

func (x *SearchMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SearchMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Отметить как прочитанное
type MarkAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                          // Будет из контекста, но оставим для ясности
	UpToMessageId int64                  `protobuf:"varint,3,opt,name=up_to_message_id,json=upToMessageId,proto3" json:"up_to_message_id,omitempty"` // До какого сообщения прочитано
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{14}
}

func (x *MarkAsReadRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *MarkAsReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkAsReadRequest) GetUpToMessageId() int64 {
	if x != nil {
		return x.UpToMessageId
	}
	return 0
}

// Непрочитанные сообщения
type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{15}
}

func (x *GetUnreadCountRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetUnreadCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	LastMessageId int64                  `protobuf:"varint,2,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"` // ID последнего непрочитанного
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{16}
}

func (x *GetUnreadCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetUnreadCountResponse) GetLastMessageId() int64 {
	if x != nil {
		return x.LastMessageId
	}
	return 0
}

// WebSocket
type ConnectWebSocketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // JWT токен для аутентификации
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectWebSocketRequest) Reset() {
	*x = ConnectWebSocketRequest{}
	mi := &file_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectWebSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectWebSocketRequest) ProtoMessage() {}

func (x *ConnectWebSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectWebSocketRequest.ProtoReflect.Descriptor instead.
func (*ConnectWebSocketRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{17}
}

func (x *ConnectWebSocketRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ConnectWebSocketRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConnectWebSocketRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type WebSocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*WebSocketMessage_NewMessage
	//	*WebSocketMessage_MessageUpdated
	//	*WebSocketMessage_MessageDeleted
	//	*WebSocketMessage_ReactionAdded
	//	*WebSocketMessage_ReactionRemoved
	//	*WebSocketMessage_Typing
	//	*WebSocketMessage_ReadReceipt
	Event         isWebSocketMessage_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{18}
}

func (x *WebSocketMessage) GetEvent() isWebSocketMessage_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WebSocketMessage) GetNewMessage() *NewMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*WebSocketMessage_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

func (x *WebSocketMessage) GetMessageUpdated() *MessageUpdatedEvent {
	if x != nil {
		if x, ok := x.Event.(*WebSocketMessage_MessageUpdated); ok {
			return x.MessageUpdated
		}
	}
	return nil
}

func (x *WebSocketMessage) GetMessageDeleted() *MessageDeletedEvent {
	if x != nil {
		if x, ok := x.Event.(*WebSocketMessage_MessageDeleted); ok {
			return x.MessageDeleted
		}
	}
	return nil
}

func (x *WebSocketMessage) GetReactionAdded() *ReactionAddedEvent {
	if x != nil {
		if x, ok := x.Event.(*WebSocketMessage_ReactionAdded); ok {
			return x.ReactionAdded
		}
	}
	return nil
}

func (x *WebSocketMessage) GetReactionRemoved() *ReactionRemovedEvent {
	if x != nil {
		if x, ok := x.Event.(*WebSocketMessage_ReactionRemoved); ok {
			return x.ReactionRemoved
		}
	}
	return nil
}

func (x *WebSocketMessage) GetTyping() *TypingEvent {
	if x != nil {
		if x, ok := x.Event.(*WebSocketMessage_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *WebSocketMessage) GetReadReceipt() *ReadReceiptEvent {
	if x != nil {
		if x, ok := x.Event.(*WebSocketMessage_ReadReceipt); ok {
			return x.ReadReceipt
		}
	}
	return nil
}

type isWebSocketMessage_Event interface {
	isWebSocketMessage_Event()
}

type WebSocketMessage_NewMessage struct {
	NewMessage *NewMessageEvent `protobuf:"bytes,1,opt,name=new_message,json=newMessage,proto3,oneof"`
}

type WebSocketMessage_MessageUpdated struct {
	MessageUpdated *MessageUpdatedEvent `protobuf:"bytes,2,opt,name=message_updated,json=messageUpdated,proto3,oneof"`
}

type WebSocketMessage_MessageDeleted struct {
	MessageDeleted *MessageDeletedEvent `protobuf:"bytes,3,opt,name=message_deleted,json=messageDeleted,proto3,oneof"`
}

type WebSocketMessage_ReactionAdded struct {
	ReactionAdded *ReactionAddedEvent `protobuf:"bytes,4,opt,name=reaction_added,json=reactionAdded,proto3,oneof"`
}

type WebSocketMessage_ReactionRemoved struct {
	ReactionRemoved *ReactionRemovedEvent `protobuf:"bytes,5,opt,name=reaction_removed,json=reactionRemoved,proto3,oneof"`
}

type WebSocketMessage_Typing struct {
	Typing *TypingEvent `protobuf:"bytes,6,opt,name=typing,proto3,oneof"`
}

type WebSocketMessage_ReadReceipt struct {
	ReadReceipt *ReadReceiptEvent `protobuf:"bytes,7,opt,name=read_receipt,json=readReceipt,proto3,oneof"`
}

func (*WebSocketMessage_NewMessage) isWebSocketMessage_Event() {}

func (*WebSocketMessage_MessageUpdated) isWebSocketMessage_Event() {}

func (*WebSocketMessage_MessageDeleted) isWebSocketMessage_Event() {}

func (*WebSocketMessage_ReactionAdded) isWebSocketMessage_Event() {}

func (*WebSocketMessage_ReactionRemoved) isWebSocketMessage_Event() {}

func (*WebSocketMessage_Typing) isWebSocketMessage_Event() {}

func (*WebSocketMessage_ReadReceipt) isWebSocketMessage_Event() {}

// Внутренние методы
type GetLastMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastMessageRequest) Reset() {
	*x = GetLastMessageRequest{}
	mi := &file_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastMessageRequest) ProtoMessage() {}

func (x *GetLastMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastMessageRequest.ProtoReflect.Descriptor instead.
func (*GetLastMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{19}
}

func (x *GetLastMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type DeleteChatMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatMessagesRequest) Reset() {
	*x = DeleteChatMessagesRequest{}
	mi := &file_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatMessagesRequest) ProtoMessage() {}

func (x *DeleteChatMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatMessagesRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatMessagesRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteChatMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

// Сообщение
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type          MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=message.v1.MessageType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsEdited      bool                   `protobuf:"varint,8,opt,name=is_edited,json=isEdited,proto3" json:"is_edited,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,9,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	ReplyTo       int64                  `protobuf:"varint,10,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`                                                                // ID сообщения, на которое отвечаем
	ReplyInfo     *ReplyInfo             `protobuf:"bytes,11,opt,name=reply_info,json=replyInfo,proto3" json:"reply_info,omitempty"`                                                           // Информация о сообщении-ответе
	Attachments   []int64                `protobuf:"varint,12,rep,packed,name=attachments,proto3" json:"attachments,omitempty"`                                                                // Список ID вложений
	Reactions     map[string]int32       `protobuf:"bytes,13,rep,name=reactions,proto3" json:"reactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Счётчики реакций { "❤️": 5, "👍": 2 }
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{21}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Message) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Message) GetIsEdited() bool {
	if x != nil {
		return x.IsEdited
	}
	return false
}

func (x *Message) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Message) GetReplyTo() int64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

func (x *Message) GetReplyInfo() *ReplyInfo {
	if x != nil {
		return x.ReplyInfo
	}
	return nil
}

func (x *Message) GetAttachments() []int64 {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Message) GetReactions() map[string]int32 {
	if x != nil {
		return x.Reactions
	}
	return nil
}

// Информация о сообщении-ответе (опционально, подгружается при запросе)
type ReplyInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderName     string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`             // Имя отправителя (из User Service)
	ContentPreview string                 `protobuf:"bytes,3,opt,name=content_preview,json=contentPreview,proto3" json:"content_preview,omitempty"` // Превью текста (первые 50 символов)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplyInfo) Reset() {
	*x = ReplyInfo{}
	mi := &file_message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyInfo) ProtoMessage() {}

func (x *ReplyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyInfo.ProtoReflect.Descriptor instead.
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{22}
}

func (x *ReplyInfo) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReplyInfo) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ReplyInfo) GetContentPreview() string {
	if x != nil {
		return x.ContentPreview
	}
	return ""
}

// Реакция
type Reaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reaction      string                 `protobuf:"bytes,3,opt,name=reaction,proto3" json:"reaction,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_message_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{23}
}

func (x *Reaction) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Reaction) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Reaction) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

func (x *Reaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Новое сообщение
type NewMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessageEvent) Reset() {
	*x = NewMessageEvent{}
	mi := &file_message_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessageEvent) ProtoMessage() {}

func (x *NewMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessageEvent.ProtoReflect.Descriptor instead.
func (*NewMessageEvent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{24}
}

func (x *NewMessageEvent) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// Обновление сообщения
type MessageUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	NewContent    string                 `protobuf:"bytes,2,opt,name=new_content,json=newContent,proto3" json:"new_content,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUpdatedEvent) Reset() {
	*x = MessageUpdatedEvent{}
	mi := &file_message_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdatedEvent) ProtoMessage() {}

func (x *MessageUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdatedEvent.ProtoReflect.Descriptor instead.
func (*MessageUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{25}
}

func (x *MessageUpdatedEvent) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageUpdatedEvent) GetNewContent() string {
	if x != nil {
		return x.NewContent
	}
	return ""
}

func (x *MessageUpdatedEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Удаление сообщения
type MessageDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ForEveryone   bool                   `protobuf:"varint,2,opt,name=for_everyone,json=forEveryone,proto3" json:"for_everyone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeletedEvent) Reset() {
	*x = MessageDeletedEvent{}
	mi := &file_message_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeletedEvent) ProtoMessage() {}

func (x *MessageDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeletedEvent.ProtoReflect.Descriptor instead.
func (*MessageDeletedEvent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{26}
}

func (x *MessageDeletedEvent) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageDeletedEvent) GetForEveryone() bool {
	if x != nil {
		return x.ForEveryone
	}
	return false
}

// Добавлена реакция
type ReactionAddedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reaction      string                 `protobuf:"bytes,3,opt,name=reaction,proto3" json:"reaction,omitempty"`
	NewCount      int32                  `protobuf:"varint,4,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionAddedEvent) Reset() {
	*x = ReactionAddedEvent{}
	mi := &file_message_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionAddedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionAddedEvent) ProtoMessage() {}

func (x *ReactionAddedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionAddedEvent.ProtoReflect.Descriptor instead.
func (*ReactionAddedEvent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{27}
}

func (x *ReactionAddedEvent) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReactionAddedEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReactionAddedEvent) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

func (x *ReactionAddedEvent) GetNewCount() int32 {
	if x != nil {
		return x.NewCount
	}
	return 0
}

// Удалена реакция
type ReactionRemovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reaction      string                 `protobuf:"bytes,3,opt,name=reaction,proto3" json:"reaction,omitempty"`
	NewCount      int32                  `protobuf:"varint,4,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionRemovedEvent) Reset() {
	*x = ReactionRemovedEvent{}
	mi := &file_message_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionRemovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionRemovedEvent) ProtoMessage() {}

func (x *ReactionRemovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionRemovedEvent.ProtoReflect.Descriptor instead.
func (*ReactionRemovedEvent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{28}
}

func (x *ReactionRemovedEvent) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReactionRemovedEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReactionRemovedEvent) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

func (x *ReactionRemovedEvent) GetNewCount() int32 {
	if x != nil {
		return x.NewCount
	}
	return 0
}

// Пользователь печатает
type TypingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	IsTyping      bool                   `protobuf:"varint,4,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"` // true - начал печатать, false - перестал
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingEvent) Reset() {
	*x = TypingEvent{}
	mi := &file_message_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingEvent) ProtoMessage() {}

func (x *TypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingEvent.ProtoReflect.Descriptor instead.
func (*TypingEvent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{29}
}

func (x *TypingEvent) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *TypingEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TypingEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TypingEvent) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

// Подтверждение прочтения
type ReadReceiptEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChatId            int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId            int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReadUpToMessageId string                 `protobuf:"bytes,3,opt,name=read_up_to_message_id,json=readUpToMessageId,proto3" json:"read_up_to_message_id,omitempty"`
	ReadAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReadReceiptEvent) Reset() {
	*x = ReadReceiptEvent{}
	mi := &file_message_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceiptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceiptEvent) ProtoMessage() {}

func (x *ReadReceiptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceiptEvent.ProtoReflect.Descriptor instead.
func (*ReadReceiptEvent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{30}
}

func (x *ReadReceiptEvent) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ReadReceiptEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReadReceiptEvent) GetReadUpToMessageId() string {
	if x != nil {
		return x.ReadUpToMessageId
	}
	return ""
}

func (x *ReadReceiptEvent) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\n" +
	"message.v1\x1a\x0ftimestamp.proto\"\a\n" +
	"\x05Empty\"\xb1\x01\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.message.v1.MessageTypeR\x04type\x12\x19\n" +
	"\breply_to\x18\x04 \x01(\x03R\areplyTo\x12 \n" +
	"\vattachments\x18\x05 \x03(\x03R\vattachments\"q\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06before\x18\x03 \x01(\x03R\x06before\x12\x14\n" +
	"\x05after\x18\x04 \x01(\x03R\x05after\"\x82\x01\n" +
	"\x13GetMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.message.v1.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"M\n" +
	"\x12EditMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"X\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12!\n" +
	"\ffor_everyone\x18\x02 \x01(\bR\vforEveryone\"2\n" +
	"\x11GetMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"O\n" +
	"\x12AddReactionRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1a\n" +
	"\breaction\x18\x02 \x01(\tR\breaction\"R\n" +
	"\x15RemoveReactionRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1a\n" +
	"\breaction\x18\x02 \x01(\tR\breaction\"4\n" +
	"\x13GetReactionsRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"\xbe\x01\n" +
	"\x14GetReactionsResponse\x12M\n" +
	"\treactions\x18\x01 \x03(\v2/.message.v1.GetReactionsResponse.ReactionsEntryR\treactions\x1aW\n" +
	"\x0eReactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.message.v1.ReactionCountR\x05value:\x028\x01\"\\\n" +
	"\rReactionCount\x12\x1a\n" +
	"\breaction\x18\x01 \x01(\tR\breaction\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\x03R\auserIds\"t\n" +
	"\x15SearchMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06before\x18\x04 \x01(\x03R\x06before\"d\n" +
	"\x16SearchMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.message.v1.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"n\n" +
	"\x11MarkAsReadRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12'\n" +
	"\x10up_to_message_id\x18\x03 \x01(\x03R\rupToMessageId\"I\n" +
	"\x15GetUnreadCountRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"V\n" +
	"\x16GetUnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12&\n" +
	"\x0flast_message_id\x18\x02 \x01(\x03R\rlastMessageId\"a\n" +
	"\x17ConnectWebSocketRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x81\x04\n" +
	"\x10WebSocketMessage\x12>\n" +
	"\vnew_message\x18\x01 \x01(\v2\x1b.message.v1.NewMessageEventH\x00R\n" +
	"newMessage\x12J\n" +
	"\x0fmessage_updated\x18\x02 \x01(\v2\x1f.message.v1.MessageUpdatedEventH\x00R\x0emessageUpdated\x12J\n" +
	"\x0fmessage_deleted\x18\x03 \x01(\v2\x1f.message.v1.MessageDeletedEventH\x00R\x0emessageDeleted\x12G\n" +
	"\x0ereaction_added\x18\x04 \x01(\v2\x1e.message.v1.ReactionAddedEventH\x00R\rreactionAdded\x12M\n" +
	"\x10reaction_removed\x18\x05 \x01(\v2 .message.v1.ReactionRemovedEventH\x00R\x0freactionRemoved\x121\n" +
	"\x06typing\x18\x06 \x01(\v2\x17.message.v1.TypingEventH\x00R\x06typing\x12A\n" +
	"\fread_receipt\x18\a \x01(\v2\x1c.message.v1.ReadReceiptEventH\x00R\vreadReceiptB\a\n" +
	"\x05event\"0\n" +
	"\x15GetLastMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"4\n" +
	"\x19DeleteChatMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"\xbb\x04\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12+\n" +
	"\x04type\x18\x05 \x01(\x0e2\x17.message.v1.MessageTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tis_edited\x18\b \x01(\bR\bisEdited\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\t \x01(\bR\tisDeleted\x12\x19\n" +
	"\breply_to\x18\n" +
	" \x01(\x03R\areplyTo\x124\n" +
	"\n" +
	"reply_info\x18\v \x01(\v2\x15.message.v1.ReplyInfoR\treplyInfo\x12 \n" +
	"\vattachments\x18\f \x03(\x03R\vattachments\x12@\n" +
	"\treactions\x18\r \x03(\v2\".message.v1.Message.ReactionsEntryR\treactions\x1a<\n" +
	"\x0eReactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"t\n" +
	"\tReplyInfo\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12'\n" +
	"\x0fcontent_preview\x18\x03 \x01(\tR\x0econtentPreview\"\x99\x01\n" +
	"\bReaction\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\breaction\x18\x03 \x01(\tR\breaction\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"@\n" +
	"\x0fNewMessageEvent\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.message.v1.MessageR\amessage\"\x90\x01\n" +
	"\x13MessageUpdatedEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1f\n" +
	"\vnew_content\x18\x02 \x01(\tR\n" +
	"newContent\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"W\n" +
	"\x13MessageDeletedEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12!\n" +
	"\ffor_everyone\x18\x02 \x01(\bR\vforEveryone\"\x85\x01\n" +
	"\x12ReactionAddedEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\breaction\x18\x03 \x01(\tR\breaction\x12\x1b\n" +
	"\tnew_count\x18\x04 \x01(\x05R\bnewCount\"\x87\x01\n" +
	"\x14ReactionRemovedEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\breaction\x18\x03 \x01(\tR\breaction\x12\x1b\n" +
	"\tnew_count\x18\x04 \x01(\x05R\bnewCount\"x\n" +
	"\vTypingEvent\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\tis_typing\x18\x04 \x01(\bR\bisTyping\"\xab\x01\n" +
	"\x10ReadReceiptEvent\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x120\n" +
	"\x15read_up_to_message_id\x18\x03 \x01(\tR\x11readUpToMessageId\x123\n" +
	"\aread_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt*\xa0\x01\n" +
	"\vMessageType\x12\x18\n" +
	"\x14MESSAGE_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x02\x12\x15\n" +
	"\x11MESSAGE_TYPE_FILE\x10\x03\x12\x18\n" +
	"\x14MESSAGE_TYPE_STICKER\x10\x04\x12\x17\n" +
	"\x13MESSAGE_TYPE_SYSTEM\x10\x052\xe6\a\n" +
	"\x0eMessageService\x12B\n" +
	"\vSendMessage\x12\x1e.message.v1.SendMessageRequest\x1a\x13.message.v1.Message\x12N\n" +
	"\vGetMessages\x12\x1e.message.v1.GetMessagesRequest\x1a\x1f.message.v1.GetMessagesResponse\x12B\n" +
	"\vEditMessage\x12\x1e.message.v1.EditMessageRequest\x1a\x13.message.v1.Message\x12D\n" +
	"\rDeleteMessage\x12 .message.v1.DeleteMessageRequest\x1a\x11.message.v1.Empty\x12@\n" +
	"\n" +
	"GetMessage\x12\x1d.message.v1.GetMessageRequest\x1a\x13.message.v1.Message\x12C\n" +
	"\vAddReaction\x12\x1e.message.v1.AddReactionRequest\x1a\x14.message.v1.Reaction\x12F\n" +
	"\x0eRemoveReaction\x12!.message.v1.RemoveReactionRequest\x1a\x11.message.v1.Empty\x12W\n" +
	"\x0eSearchMessages\x12!.message.v1.SearchMessagesRequest\x1a\".message.v1.SearchMessagesResponse\x12>\n" +
	"\n" +
	"MarkAsRead\x12\x1d.message.v1.MarkAsReadRequest\x1a\x11.message.v1.Empty\x12W\n" +
	"\x0eGetUnreadCount\x12!.message.v1.GetUnreadCountRequest\x1a\".message.v1.GetUnreadCountResponse\x12W\n" +
	"\x10ConnectWebSocket\x12#.message.v1.ConnectWebSocketRequest\x1a\x1c.message.v1.WebSocketMessage0\x01\x12J\n" +
	"\x0eGetLastMessage\x12!.message.v1.GetLastMessageRequest\x1a\x13.message.v1.Message\"\x00\x12P\n" +
	"\x12DeleteChatMessages\x12%.message.v1.DeleteChatMessagesRequest\x1a\x11.message.v1.Empty\"\x00BEZCgithub.com/north-fy/talker/services/message/pkg/protos/v1;messagev1b\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_message_proto_goTypes = []any{
	(MessageType)(0),                  // 0: message.v1.MessageType
	(*Empty)(nil),                     // 1: message.v1.Empty
	(*SendMessageRequest)(nil),        // 2: message.v1.SendMessageRequest
	(*GetMessagesRequest)(nil),        // 3: message.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),       // 4: message.v1.GetMessagesResponse
	(*EditMessageRequest)(nil),        // 5: message.v1.EditMessageRequest
	(*DeleteMessageRequest)(nil),      // 6: message.v1.DeleteMessageRequest
	(*GetMessageRequest)(nil),         // 7: message.v1.GetMessageRequest
	(*AddReactionRequest)(nil),        // 8: message.v1.AddReactionRequest
	(*RemoveReactionRequest)(nil),     // 9: message.v1.RemoveReactionRequest
	(*GetReactionsRequest)(nil),       // 10: message.v1.GetReactionsRequest
	(*GetReactionsResponse)(nil),      // 11: message.v1.GetReactionsResponse
	(*ReactionCount)(nil),             // 12: message.v1.ReactionCount
	(*SearchMessagesRequest)(nil),     // 13: message.v1.SearchMessagesRequest
	(*SearchMessagesResponse)(nil),    // 14: message.v1.SearchMessagesResponse
	(*MarkAsReadRequest)(nil),         // 15: message.v1.MarkAsReadRequest
	(*GetUnreadCountRequest)(nil),     // 16: message.v1.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),    // 17: message.v1.GetUnreadCountResponse
	(*ConnectWebSocketRequest)(nil),   // 18: message.v1.ConnectWebSocketRequest
	(*WebSocketMessage)(nil),          // 19: message.v1.WebSocketMessage
	(*GetLastMessageRequest)(nil),     // 20: message.v1.GetLastMessageRequest
	(*DeleteChatMessagesRequest)(nil), // 21: message.v1.DeleteChatMessagesRequest
	(*Message)(nil),                   // 22: message.v1.Message
	(*ReplyInfo)(nil),                 // 23: message.v1.ReplyInfo
	(*Reaction)(nil),                  // 24: message.v1.Reaction
	(*NewMessageEvent)(nil),           // 25: message.v1.NewMessageEvent
	(*MessageUpdatedEvent)(nil),       // 26: message.v1.MessageUpdatedEvent
	(*MessageDeletedEvent)(nil),       // 27: message.v1.MessageDeletedEvent
	(*ReactionAddedEvent)(nil),        // 28: message.v1.ReactionAddedEvent
	(*ReactionRemovedEvent)(nil),      // 29: message.v1.ReactionRemovedEvent
	(*TypingEvent)(nil),               // 30: message.v1.TypingEvent
	(*ReadReceiptEvent)(nil),          // 31: message.v1.ReadReceiptEvent
	nil,                               // 32: message.v1.GetReactionsResponse.ReactionsEntry
	nil,                               // 33: message.v1.Message.ReactionsEntry
	(*timestamppb.Timestamp)(nil),     // 34: google.protobuf.Timestamp
}
var file_message_proto_depIdxs = []int32{
	0,  // 0: message.v1.SendMessageRequest.type:type_name -> message.v1.MessageType
	22, // 1: message.v1.GetMessagesResponse.messages:type_name -> message.v1.Message
	32, // 2: message.v1.GetReactionsResponse.reactions:type_name -> message.v1.GetReactionsResponse.ReactionsEntry
	22, // 3: message.v1.SearchMessagesResponse.messages:type_name -> message.v1.Message
	25, // 4: message.v1.WebSocketMessage.new_message:type_name -> message.v1.NewMessageEvent
	26, // 5: message.v1.WebSocketMessage.message_updated:type_name -> message.v1.MessageUpdatedEvent
	27, // 6: message.v1.WebSocketMessage.message_deleted:type_name -> message.v1.MessageDeletedEvent
	28, // 7: message.v1.WebSocketMessage.reaction_added:type_name -> message.v1.ReactionAddedEvent
	29, // 8: message.v1.WebSocketMessage.reaction_removed:type_name -> message.v1.ReactionRemovedEvent
	30, // 9: message.v1.WebSocketMessage.typing:type_name -> message.v1.TypingEvent
	31, // 10: message.v1.WebSocketMessage.read_receipt:type_name -> message.v1.ReadReceiptEvent
	0,  // 11: message.v1.Message.type:type_name -> message.v1.MessageType
	34, // 12: message.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	34, // 13: message.v1.Message.updated_at:type_name -> google.protobuf.Timestamp
	23, // 14: message.v1.Message.reply_info:type_name -> message.v1.ReplyInfo
	33, // 15: message.v1.Message.reactions:type_name -> message.v1.Message.ReactionsEntry
	34, // 16: message.v1.Reaction.created_at:type_name -> google.protobuf.Timestamp
	22, // 17: message.v1.NewMessageEvent.message:type_name -> message.v1.Message
	34, // 18: message.v1.MessageUpdatedEvent.updated_at:type_name -> google.protobuf.Timestamp
	34, // 19: message.v1.ReadReceiptEvent.read_at:type_name -> google.protobuf.Timestamp
	12, // 20: message.v1.GetReactionsResponse.ReactionsEntry.value:type_name -> message.v1.ReactionCount
	2,  // 21: message.v1.MessageService.SendMessage:input_type -> message.v1.SendMessageRequest
	3,  // 22: message.v1.MessageService.GetMessages:input_type -> message.v1.GetMessagesRequest
	5,  // 23: message.v1.MessageService.EditMessage:input_type -> message.v1.EditMessageRequest
	6,  // 24: message.v1.MessageService.DeleteMessage:input_type -> message.v1.DeleteMessageRequest
	7,  // 25: message.v1.MessageService.GetMessage:input_type -> message.v1.GetMessageRequest
	8,  // 26: message.v1.MessageService.AddReaction:input_type -> message.v1.AddReactionRequest
	9,  // 27: message.v1.MessageService.RemoveReaction:input_type -> message.v1.RemoveReactionRequest
	13, // 28: message.v1.MessageService.SearchMessages:input_type -> message.v1.SearchMessagesRequest
	15, // 29: message.v1.MessageService.MarkAsRead:input_type -> message.v1.MarkAsReadRequest
	16, // 30: message.v1.MessageService.GetUnreadCount:input_type -> message.v1.GetUnreadCountRequest
	18, // 31: message.v1.MessageService.ConnectWebSocket:input_type -> message.v1.ConnectWebSocketRequest
	20, // 32: message.v1.MessageService.GetLastMessage:input_type -> message.v1.GetLastMessageRequest
	21, // 33: message.v1.MessageService.DeleteChatMessages:input_type -> message.v1.DeleteChatMessagesRequest
	22, // 34: message.v1.MessageService.SendMessage:output_type -> message.v1.Message
	4,  // 35: message.v1.MessageService.GetMessages:output_type -> message.v1.GetMessagesResponse
	22, // 36: message.v1.MessageService.EditMessage:output_type -> message.v1.Message
	1,  // 37: message.v1.MessageService.DeleteMessage:output_type -> message.v1.Empty
	22, // 38: message.v1.MessageService.GetMessage:output_type -> message.v1.Message
	24, // 39: message.v1.MessageService.AddReaction:output_type -> message.v1.Reaction
	1,  // 40: message.v1.MessageService.RemoveReaction:output_type -> message.v1.Empty
	14, // 41: message.v1.MessageService.SearchMessages:output_type -> message.v1.SearchMessagesResponse
	1,  // 42: message.v1.MessageService.MarkAsRead:output_type -> message.v1.Empty
	17, // 43: message.v1.MessageService.GetUnreadCount:output_type -> message.v1.GetUnreadCountResponse
	19, // 44: message.v1.MessageService.ConnectWebSocket:output_type -> message.v1.WebSocketMessage
	22, // 45: message.v1.MessageService.GetLastMessage:output_type -> message.v1.Message
	1,  // 46: message.v1.MessageService.DeleteChatMessages:output_type -> message.v1.Empty
	34, // [34:47] is the sub-list for method output_type
	21, // [21:34] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[18].OneofWrappers = []any{
		(*WebSocketMessage_NewMessage)(nil),
		(*WebSocketMessage_MessageUpdated)(nil),
		(*WebSocketMessage_MessageDeleted)(nil),
		(*WebSocketMessage_ReactionAdded)(nil),
		(*WebSocketMessage_ReactionRemoved)(nil),
		(*WebSocketMessage_Typing)(nil),
		(*WebSocketMessage_ReadReceipt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
